import db

db.cursor.execute("SELECT city_name from countries")
record = db.cursor.fetchall()
result = []
for el in record:
    result.append(el[0])

cities_eng = ["Buenos Aires", "Mexico City", "Medellín", "Guadalajara", "Lima", "Cuenca", "Havana", "São Paulo",
              "Rio de Janeiro", "Oaxaca", "Cancun", "Galapagos Islands", "Florianopolis", "Queretaro", "Cordoba",
              "Santiago", "Puerto Escondido", "Porto Alegre", "Monterrey", "Belo Horizonte", "Paramaribo", "Antigua",
              "Merida", "Rosario", "Quito", "Playa del Carmen", "Bogota", "Asuncion", "Willemstad", "Fortaleza",
              "Natal",
              "Cartagena", "La Paz", "Guanajuato", "Minca", "Arequipa", "Santa Cruz", "San José", "La Paz", "Goiania",
              "Hermosillo", "Santo Domingo", "Curitiba", "Panama City", "San Miguel de Allende", "La Serena",
              "San Juan",
              "Cochabamba", "Salta", "Mendoza", "Tijuana", "Belem", "Intag Valley", "El Alto", "Cusco", "Ushuaia",
              "Campinas", "Guayaquil", "Mar del Plata", "Toluca", "Uberlandia", "Bucaramanga", "Guatemala City",
              "Recife",
              "San Luis Potosi", "Chachapoyas", "Pasto", "Cali", "Puebla", "Montevideo", "Campos dos Goytacazes",
              "Salento",
              "Sao Luis", "León", "Liberia", "Salvador", "San Cristóbal de las Casas", "Brasilia", "Barranquilla",
              "São José dos Campos", "Tulum", "Itapema", "Vitória", "Port-au-Prince", "Cozumel", "Maracaibo",
              "San Juan del Sur", "Panajachel", "Juarez", "Campo Grande", "La Plata", "Managua", "Anápolis",
              "Georgetown",
              "Cabarete", "Maracay", "Santa Marta", "Caye Caulker", "Sorocaba", "Valparaíso", "Kingston",
              "Puerto Vallarta",
              "San Salvador", "Mexicali", "Tegucigalpa", "Torreon", "Bocas del Toro", "Oranjestad", "Joao Pessoa",
              "Montanita", "Puerto Viejo", "Belize City", "Jundiaí", "Manaus", "San Pedro Sula", "Caracas", "Sayulita",
              "George Town", "Santa Teresa", "Iquique", "San Ignacio", "Aguascalientes", "Copan", "Jarabacoa",
              "Road Town",
              "Mancora", "Port of Spain", "Punta del Este", "Viña del Mar", "Stanley", "Montego Bay", "Nassau",
              "Hamilton",
              "Antofagasta", "Kralendijk", "Charlotte Amalie", "Philipsburg", "Basse-Terre", "Bridgetown",
              "King Edward Point", "Bay Islands", "St John's", "Cayenne", "Tamarindo", "San Pedro de Atacama",
              "San Pedro",
              "Isla Mujeres", "Martinique", "Punta Cana", "Cabo San Lucas", "Tabaranã do Norte", "San Antonio",
              "Atlanta",
              "Dallas", "New York City", "Tucson", "Tampa", "Vancouver", "Austin", "Salt Lake City", "Toronto",
              "Nashville",
              "Gainesville", "Minneapolis", "Winnipeg", "Beaumont", "Fayetteville", "Brownsville", "Battle Creek",
              "Grande Prairie", "Los Angeles", "Jonesboro", "Las Vegas", "Calgary", "Buffalo", "Waterloo", "Dothan",
              "Lubbock", "Windsor", "Columbus", "Houston", "Wichita", "Conroe", "Youngstown", "Washington",
              "Port Arthur",
              "Raleigh", "Amarillo", "Kokomo", "Chatham", "North Little Rock", "Longview", "Macon", "Harlingen",
              "Killeen",
              "Odessa", "San Diego", "Albuquerque", "Lawton", "Davenport", "Indianapolis", "Syracuse", "Joplin",
              "Laredo",
              "Montgomery", "Bowling Green", "Las Cruces", "Boston", "Elkhart", "Jacksonville", "Tulsa", "Jacksonville",
              "Regina", "New Orleans", "Surrey", "Ogden", "Kitchener", "Cincinnati", "Victoria", "Seattle",
              "Bossier City",
              "McAllen", "San Francisco", "Muncie", "Conway", "Roanoke", "Tyler", "Fort Smith", "Bedford", "Pittsburgh",
              "Salem", "Yuma", "Portland", "Oklahoma City", "Knoxville", "Lancaster", "Saskatoon", "Shreveport",
              "Chico",
              "Evansville", "Burlington", "Mission", "Grand Forks", "Madison", "Palm Coast", "Victorville", "Flint",
              "Pharr", "Lafayette", "Norfolk", "Grand Rapids", "Denver", "Kingsport", "Colorado Springs", "Owensboro",
              "Temple", "Enid", "Lincoln", "Cleveland", "Quebec City", "Rocky Mount", "Oregon City", "Fargo",
              "High Point",
              "Guelph", "Pasco", "Richmond", "Chattanooga", "Modesto", "Palm Bay", "Idaho Falls", "Birmingham",
              "Abbotsford", "Fort Wayne", "Fresno", "Rochester", "Lethbridge", "Albany", "Miami", "Ashland", "Richland",
              "Scranton", "Winston", "Pocatello", "Aurora", "Valdosta", "Decatur", "Palmdale", "Columbus", "Rogers",
              "Reading", "Victoria", "Hoover", "Grand Island", "Wichita Falls", "Huntsville", "Bismarck", "Chicago",
              "Johnson City", "Edinburg", "Bethlehem", "Pensacola", "Porterville", "Cedar Rapids", "Baton Rouge",
              "Pueblo",
              "Little Rock", "Mobile", "Casper", "Montreal", "Springdale", "Hesperia", "Vineland", "Beacon",
              "St. Cloud",
              "St. Joseph", "Provo", "Clarksville", "Bridgeton", "Ocala", "Waco", "Oakland", "Turlock", "Kearney",
              "Columbia", "Rockford", "Minot", "Yakima", "Moncton", "Corpus Christi", "Topeka", "Allentown", "Lodi",
              "Kelowna", "Des Moines", "Terre Haute", "Kennewick", "Erie", "Hartford", "Springfield", "Yuba City",
              "Providence", "Utica", "Asheville", "Bridgeport", "Barrie", "Toledo", "Kenosha", "Dubuque", "Tulare",
              "Eau Claire", "Peoria", "Visalia", "Boulder", "Fredericton", "Casa Grande", "Waukegan", "Lawrence",
              "Warner Robins", "Apple Valley", "Lynchburg", "Memphis", "Milwaukee", "Janesville", "Oshawa",
              "Bakersfield",
              "Anchorage", "Charlotte", "Jackson", "Scottsdale", "Reno", "Carson City", "Rochester", "Medford",
              "Greensboro", "Normal", "Nanaimo", "Omaha", "Sioux Falls", "Billings", "Manchester", "Manteca", "Abilene",
              "Bloomington", "Melbourne", "Fairfield", "Corvallis", "Hemet", "Helena", "Champaign", "Merced",
              "Lexington",
              "New Haven", "Detroit", "Lansing", "Boise", "St. Louis", "Cheyenne", "Bloomington", "Redding",
              "Marysville",
              "Stockton", "Wilmington", "Greenville", "Phoenix", "Louisville", "Frederick", "Great Falls", "Appleton",
              "Augusta", "Bryan", "Delano", "Missoula", "Brampton", "Olympia", "Eugene", "Fort Collins", "Schenectady",
              "Iowa City", "College Station", "Bellingham", "Grand Junction", "Santa Fe", "St. Catharines", "Anderson",
              "Lake Havasu City", "Tracy", "Joliet", "Logan", "Spokane Valley", "Greeley", "Orlando", "Sparks", "Elgin",
              "Fort Lauderdale", "Philadelphia", "Tallahassee", "Worcester", "Sioux City", "Oshkosh", "Revelstoke",
              "Spokane", "Virginia Beach", "Weston", "Bend", "Key West", "Harrisonburg", "Ottawa", "Rapid City",
              "San Jose",
              "Cody", "Sacramento", "Sandpoint", "Bellevue", "Manhattan", "Fort McMurray", "Kansas City", "Taos",
              "West Palm Beach", "Ann Arbor", "Palo Alto", "Duluth", "Nashua", "Santa Barbara", "Green Bay",
              "Flagstaff",
              "Gulfport", "Mountain View", "Coeur d'Alene", "Fairfax", "Midland", "Charleston", "Ithaca", "Baltimore",
              "Halifax", "Riverside", "Newport Beach", "Portland", "Fort Myers", "Canton", "Princeton", "Edmonton",
              "Stamford", "Lake Tahoe", "Whistler", "Brentwood", "Menlo Park", "Port St. Lucie", "Oxnard", "Indio",
              "Monterey", "La Crosse", "Dayton", "Plantation", "Palm Desert", "Sarasota", "Park City", "Galveston",
              "Bradenton", "Cape Coral", "San Mateo", "Auburn", "Daytona Beach", "Santa Maria", "Port Orange",
              "Bonita Springs", "Savannah", "Santa Rosa", "Cathedral City", "San Angelo", "Banff", "Tuscaloosa",
              "Waterloo",
              "St. George", "Petaluma", "Enterprise", "Carlsbad", "San Clemente", "Centennial", "Lake Charles",
              "Oceanside",
              "Beaverton", "Vista", "Temecula", "Murrieta", "Henderson", "Napa", "Verdi", "Salem", "Incline Village",
              "Bozeman", "Nuuk", "Beirut", "Dubai", "Luxor", "El Gouna", "Giza", "Cairo", "Dahab", "Alexandria",
              "Amman",
              "Sharjah", "Port Said", "Kirkuk", "Ramallah", "Sulaymaniyah", "Duhok", "Qom", "Tehran", "Manama",
              "Mashhad",
              "Tabriz", "Tel Aviv", "Abu Dhabi", "Shiraz", "Isfahan", "Haifa", "Beersheba", "Kuwait City", "Erbil",
              "Doha",
              "Muscat", "Dammam", "Jeddah", "Jerusalem", "Riyadh", "Ahvaz", "Medina", "Mecca", "Mosul", "Homs", "Hama",
              "Sana'a", "Damascus", "Aleppo", "Basra", "Baghdad", "Perth", "Melbourne", "Sydney", "Auckland",
              "Honolulu",
              "Christchurch", "Wellington", "Suva", "Queenstown", "Brisbane", "Apia", "Hagatna", "Nuku'alofa",
              "Dunedin",
              "Hobart", "Adelaide", "Canberra", "Kauai", "Cairns", "Wollongong", "Hilo", "Byron Bay", "Darwin",
              "Wanaka",
              "Funafuti", "Dededo", "Honiara", "Port Vila", "Port Moresby", "Gold Coast", "Avarua", "Nouméa",
              "Cape Town",
              "Nairobi", "Taghazout", "Port Louis", "Kigali", "Johannesburg", "Marrakesh", "Harare", "Pretoria",
              "Port Elizabeth", "El Jadida", "Lagos", "Livingstone", "Dakar", "Kampala", "Fes", "Tunis", "Mombasa",
              "Benin City", "Constantine", "Kaduna", "Windhoek", "Ibadan", "Agadir", "Tangier", "Rabat", "Durban",
              "Casablanca", "Antananarivo", "Port Harcourt", "Kisangani", "Kumasi", "Boumerdas", "Algiers", "Huambo",
              "Abuja", "Lubumbashi", "Banjul", "Gaborone", "Mbuji-Mayi", "Kano", "Lome", "Zaria", "Oran", "Douala",
              "Niamey", "Essaouira", "Brazzaville", "Lilongwe", "Freetown", "Abidjan", "Tebessa", "Soweto", "Praia",
              "Conakry", "Kananga", "Luanda", "Ouagadougou", "Lusaka", "Maseru", "Yamoussoukro", "Onitsha", "Accra",
              "Laayoune", "Jamestown", "Nouakchott", "Yaounde", "Kinshasa", "Libreville", "Victoria", "Monrovia",
              "Djibouti", "N'Djamena", "Tripoli", "Juba", "Benghazi", "Khartoum", "Bangui", "Asmara", "Maputo",
              "Mogadishu",
              "Addis Ababa", "Bamako", "Dar es Salaam", "Yamoussoukro", "Onitsha", "Accra", "Laayoune", "Jamestown",
              "Nouakchott", "Yaounde", "Kinshasa", "Libreville", "Victoria", "Monrovia", "Djibouti", "N'Djamena",
              "Tripoli",
              "Juba", "Benghazi", "Khartoum", "Bangui", "Asmara", "Maputo", "Mogadishu", "Addis Ababa", "Bamako",
              "Dar es Salaam", "Yamoussoukro", "Onitsha", "Accra", "Laayoune", "Jamestown", "Nouakchott", "Yaounde",
              "Kinshasa", "Libreville", "Victoria", "Monrovia", "Djibouti", "N'Djamena", "Tripoli", "Juba", "Benghazi",
              "Khartoum", "Bangui", "Asmara", "Maputo", "Mogadishu", "Addis Ababa", "Bamako", "Dar es Salaam",
              "Bangkok",
              "Canggu", "Chiang Mai", "Kuala Lumpur", "Bengaluru", "Penang", "Ko Pha Ngan", "Kathmandu", "Da Nang",
              "Ubud",
              "Delhi", "Ho Chi Minh City", "Seminyak", "Manila", "Cebu", "Hyderabad", "Davao", "Seseh", "Seoul",
              "Hoi An",
              "Siem Reap", "Hanoi", "Palawan", "Senggigi", "Phu Quoc", "Phnom Penh", "Busan", "Haikou", "Luang Prabang",
              "Agra", "Pokhara", "Krabi", "Amritsar", "Jodhpur", "Phuket", "Jakarta", "Uluwatu", "Tashkent", "Makati",
              "General Santos", "Jaipur", "Guangzhou", "Hong Kong", "Nha Trang", "Mysore", "Kota Kinabalu", "Taipei",
              "Siargao", "Mumbai", "Colombo", "Galle", "Tainan", "Kaohsiung", "Bandung", "Lucknow", "Singapore",
              "Jeju Island", "Arugam Bay", "Pattaya", "Changzhou", "Jimbaran", "Madurai", "Goa", "Noida", "Amed",
              "Kuching",
              "Almaty", "Jamshedpur", "Sanur", "Nagpur", "Visakhapatnam", "La Union", "Kochi", "McLeod Ganj", "Kandy",
              "Gwalior", "Surabaya", "Johor Bahru", "Hubli", "Ipoh", "Malang", "Jabalpur", "Ludhiana", "Da Lat",
              "Aurangabad", "Nakhon Ratchasima", "Kalyan", "Kozhikode", "Gili Air", "Pai", "Matara", "Pekanbaru",
              "Ahmedabad", "Cirebon", "Malacca", "Mataram", "Makassar", "Vijayawada", "Ko Lanta", "Lahore", "Aligarh",
              "Kanpur", "Varkala", "Chandigarh", "Chiang Rai", "Hue", "Meerut", "Semarang", "Kota", "Vadodara", "Patna",
              "Mui Ne", "Baguio", "Ranchi", "Gurgaon", "Tirupur", "Rishikesh", "Chittagong", "Moradabad", "Daegu",
              "Ko Samui", "Medan", "Thrissur", "Ko Tao", "Palembang", "Huizhou", "Sa Pa", "Ko Chang", "Langkawi",
              "Malappuram", "Naha", "Denpasar", "Guwahati", "Yogyakarta", "Surakarta", "Khulna", "Tokyo", "Srinagar",
              "Gwangju", "Kolkata", "Varanasi", "Rajkot", "Huaibei", "Huai'an", "Huainan", "Daejeon", "Guiyang",
              "Kannur",
              "Coimbatore", "Dongying", "Lianyungang", "Jinan", "Shantou", "Kuta", "Jiamusi", "Durg", "Liuzhou",
              "Surat",
              "Vasai", "Dushanbe", "Kollam", "Suwon", "Chongqing", "Bhubaneswar", "Dongguan", "Cixi", "Multan",
              "Quanzhou",
              "Kinmen", "Changshu", "Bishkek", "Weifang", "Xi An", "Bareilly", "Anyang", "Asansol", "Bahawalpur",
              "Jilin",
              "Astana", "Jiangmen", "Gujranwala", "Hangzhou", "Nanchang", "Udon Thani", "Zhanjiang", "Kunming",
              "Nanning",
              "Islamabad", "Karachi", "Hua Hin", "Shijiazhuang", "Sialkot", "Taizhou", "Zhongshan", "Shanghai",
              "Yichang",
              "Quetta", "Chengdu", "Beijing", "Sargodha", "Rawalpindi", "Pune", "Linyi", "Vientiane", "Zunyi",
              "Zhengzhou",
              "Tangshan", "Boracay", "Nanyang", "Peshawar", "Bandar Seri Begawan", "Yangshuo", "Ningbo", "Taiyuan",
              "Xining", "Zhoukou", "Xiangtan", "Yantai", "Zhuzhou", "Hohhot", "Lanzhou", "Wenling", "Dili", "Fuzhou",
              "Zibo", "Nashik", "Faisalabad", "Shaoxing", "Handan", "Chennai", "Luoyang", "Datong", "Baoding",
              "Shenzhen",
              "Kunshan", "Taichung", "Indore", "Wuhu", "Sihanoukville", "Nanjing", "Dhaka", "Sendai", "Bhopal",
              "Qiqihar",
              "Harbin", "Putian", "Xuzhou", "Vang Vieng", "Ko Lipe", "Changchun", "Qinhuangdao", "Ao Nang", "Thane",
              "Nantong", "Tianjin", "Pyongyang", "Dhanbad", "Yinchuan", "Urumqi", "Ko Phi Phi", "Dalian", "Wonsan",
              "Fukuoka", "Zhucheng", "Zhuhai", "Thiruvananthapuram", "Zhangjiakou", "Qingdao", "Raipur", "Ulaanbaatar",
              "Chifeng", "Fushun", "Shenyang", "Wuhan", "Jiaxing", "Okayama", "Kaesong", "Kaechon", "Macau", "Hefei",
              "Kamiyama", "Guilin", "Sinuiju", "Kitakyushu", "Okinawa City", "Baotou", "Wenzhou", "Tanchon",
              "Allahabad",
              "Nagoya", "Ube", "Osaka", "Rui'an", "Xiamen", "Puning", "Tsushima Island", "Suzhou", "Nagasaki",
              "Yangzhou",
              "Zhangzhou", "Hamhung", "Kobe", "Foshan", "Changsha", "Anshan", "Chongjin", "Yiwu", "Kagoshima",
              "Zhangjiagang", "Kyoto", "Sariwon", "Ashgabat", "Huzhou", "Nampo", "Xiangyang", "Male", "Weihai",
              "Tengzhou",
              "Dorobō", "Sapporo", "Hamamatsu", "Hiroshima", "Yokohama", "Nago", "Wuxi", "Tomsk", "Vladivostok",
              "Naypyidaw", "Krasnoyarsk", "Omsk", "Mandalay", "Novosibirsk", "Kabul", "Yangon", "Lisbon",
              "Gran Canaria",
              "Timisoara", "Madeira", "Portimão", "Lagos", "Fuerteventura", "Ericeira", "Porto", "Belgrade", "Berlin",
              "Tenerife", "Warsaw", "Brasov", "Tbilisi", "Varna", "Sofia", "Istanbul", "London", "Cluj", "Wrocław",
              "Azores", "Budapest", "Bansko", "Mallorca", "Dresden", "Tallinn", "Zagreb", "Ploiesti", "Plovdiv",
              "Bucharest", "Brno", "Kraków", "Antalya", "Skopje", "Poznan", "Barcelona", "Munich", "Szczecin", "Zadar",
              "Novi Sad", "Constanta", "Mostar", "Ljubljana", "Alanya", "Athens", "Gdansk", "Braga", "Bratislava",
              "Nis",
              "Yerevan", "Groningen", "Dubrovnik", "Amsterdam", "Faro", "Adana", "Aveiro", "Leipzig", "Lodz", "Rijeka",
              "Craiova", "Riga", "Izmir", "Stockholm", "Pristina", "Alicante", "Chisinau", "Tirana", "Copenhagen",
              "Burgas",
              "Frankfurt", "Coimbra", "Split", "Menorca", "Valencia", "Kosice", "Hamburg", "Iasi", "Tampere", "Paphos",
              "Malmö", "Costa da Caparica", "Nuremberg", "Aachen", "Lublin", "Helsinki", "Ankara", "Montpellier",
              "Prague",
              "Gaziantep", "Lake Balaton", "Leiden", "Banja Luka", "Osijek", "Batumi", "Turku", "Tartu", "Sarajevo",
              "Katowice", "Oslo", "Newcastle Upon Tyne", "Rotterdam", "Edinburgh", "Gori", "Gothenburg", "Stuttgart",
              "Hagen", "Lille", "Karlsruhe", "Birmingham", "Bath", "Oulu", "Jena", "Kaunas", "Aberdeen", "Dublin",
              "Podgorica", "Graz", "Bremen", "Innsbruck", "Chania", "Toulouse", "Nottingham", "Lyon", "Zurich",
              "Cologne",
              "Baku", "Leicester", "Vilnius", "Coventry", "Vienna", "Reykjavik", "Reading", "Luton", "Geneva", "Nice",
              "Bodrum", "Madrid", "Klaipeda", "Manchester", "Northampton", "Budva", "Rzeszow", "Bournemouth", "Konya",
              "Jyvaskyla", "Venice", "Portsmouth", "Glasgow", "Nicosia", "Heidelberg", "Patras", "Espoo", "Palermo",
              "Limassol", "Šumperk", "Bristol", "Rennes", "Dortmund", "Bielefeld", "Cavtat", "A Coruna", "Paris",
              "The Hague", "Nijmegen", "Thessaloniki", "Leeds", "Utrecht", "Ghent", "Lake Como", "Brussels", "Pamplona",
              "Liverpool", "Breda", "Malaga", "Huddersfield", "Seville", "Nantes", "Oxford", "Kotor", "Cork", "Aarhus",
              "Hof", "Southampton", "Hannover", "Bern", "Galway", "Rome", "Granada", "Kassel", "Marbella", "Grenoble",
              "Hvar", "Eindhoven", "Strasbourg", "Javea", "Florence", "Cardiff", "Aalborg", "Hull", "York", "Cambridge",
              "Zwolle", "Antwerp", "Bar", "Norwich", "Scheveningen", "Milan", "Erlangen", "Tilburg", "Marseille",
              "Rhodes",
              "Leuven", "Zandvoort", "Sheffield", "Comporta", "Padova", "Monaco", "Cheltenham", "Deventer", "Trondheim",
              "Arnhem", "Shrewsbury", "Larnaca", "Leeuwarden", "Lelystad", "Lanzarote", "Bergen", "Haarlem", "Tromso",
              "Texel", "Naples", "Bordeaux", "Trieste", "Cannes", "Bruges", "Mamaia", "Lugano", "Pisa", "Gibraltar",
              "Chamonix", "San Sebastian", "Sliema", "Basel", "Andorra la Vella", "Almere", "Darmstadt", "Saint Helier",
              "Annecy", "Luxembourg", "Ibiza", "Bologna", "Trento", "Lausanne", "Bursa", "Salzburg", "Arendal",
              "Biarritz",
              "Modena", "Dusseldorf", "Genoa", "Alesund", "Rethymno", "Torshavn", "Brighton", "Interlaken", "Rovaniemi",
              "Dijon", "Santorini", "Mykonos", "Trier", "St. Gallen", "Cordoba", "Cagliari", "Avellino", "Treviso",
              "Tarifa", "Ferrara", "Rimini", "Verona", "Bilbao", "Rouen", "Lucca", "Belfast", "Amalfi", "Avignon",
              "Bari",
              "Monza", "Vatican City", "Turin", "Siena", "Ajaccio", "Exeter", "Obninsk", "Novocherkassk",
              "Ivano-Frankivsk",
              "Sochi", "Kaliningrad", "Ulyanovsk", "Izhevsk", "Krivoy-Rog", "Lviv", "Krasnodar", "Saratov", "Dnipro",
              "Odessa", "Volgograd", "Ufa", "Rostov-on-Don", "Chelyabinsk", "Kazan", "Samara", "Nizhny", "Kharkiv",
              "Yekaterinburg", "Minsk", "Kyiv", "Saint Petersburg", "Moscow", "Stuttgart", "Innopolis", "Tyumen",
              "Vladimir"]

cities_ru = [
    "Буэнос-Айрес", "Мехико", "Медельин", "Гвадалахара", "Лима", "Куэнка", "Гавана", "Сан-Паулу",
    "Рио-де-Жанейро", "Оахака", "Канкун", "Галапагосские острова", "Флорианополис", " Керетаро", "Кордова",
    "Сантьяго", "Пуэрто-Эскондидо", "Порту-Алегри", "Монтеррей", "Белу-Оризонти", "Парамарибо", "Антигуа",
    "Мерида", "Росарио", "Кито", "Плайя-дель-Кармен", "Богота", "Асунсьон", "Виллемстад", "Форталеза", "Наталь",
    "Картахена", "Ла-Пас", "Гуанахуато", "Минка", "Арекипа", "Санта-Крус", "Сан-Хосе", "Ла-Пас", "Гояния",
    "Эрмосильо", "Санто-Доминго", "Куритиба", "Панама-Сити", "Сан-Мигель-де-Альенде", "Ла-Серена", "Сан-Хуан",
    "Кочабамба", "Сальта", "Мендоса", "Тихуана", "Белем", "Интаг Вэлли", "Эль-Альто", "Куско", "Ушуайя",
    "Кампинас", "Гуаякиль", "Мар-дель-Плата", "Толука", "Уберландия", "Букараманга", "Гватемала Сити", "Ресифи",
    "Сан-Луис-Потоси", "Чачапояс", "Пасто", "Кали", "Пуэбла", "Монтевидео", "Кампус-дус-Гойтаказес", "Саленто",
    "Сан-Луис", "Леон", "Либерия", "Сальвадор", "Сан-Кристобаль-де-лас-Касас", "Бразилиа", "Барранкилья",
    "Сан-Жозе-дус-Кампус", "Тулум", "Итапема", "Витория", "Порт-о-Пренс", "Косумель", "Маракайбо",
    "Сан-Хуан-дель-Сур", "Панахачель", "Хуарес", "Кампо Гранде", "Ла Плата", "Манагуа", "Аннаполис", "Джорджтаун",
    "Кабарете", "Маракай", "Санта-Марта", "Кей Колкер", "Сорокаба", "Вальпараисо", "Кингстон", "Пуэрто-Вальярта",
    "Сан-Сальвадор", "Мехикали", "Тегусигальпа", "Торреон", "Бокас-дель-Торо", "Ораньестад", "Жоао Песоа",
    "Монтанита", "Пуэрто-Вьехо", " Белиз Город", "Джундиаи", "Манаус", "Сан-Педро-Сула", "Каракас", "Саюлита",
    "Джорджтаун", "Санта-Тереза", "Икике", "Сан-Игнасио", "Агуаскальентес", "Копан", "Харабакоа", "Роуд-Таун",
    "Манкора", "Порт-оф-Спейн", "Пунта-дель-Эсте", "Винья-дель-Мар", "Стэнли", "Монтего-Бей", "Нассау", "Гамильтон",
    "Антофагаста", "Кралендейк", "Шарлотта Амалия", "Филипсбург", "Бас-Терре", "Бриджтаун",
    "Кинг-Эдвард-Пойнт", "Острова залива", "Сент-Джонс", "Кайенна", "Тамаринд", "Сан-Педро-де-Атакама", "Сан-Педро",
    "Исла-Мухерес", "Мартиника", "Пунта-Кана", "Кабо-Сан-Лукас", "Табарана-ду-Норте", "Сан-Антонио", "Атланта",
    "Даллас", "Нью-Йорк", "Тусон", "Тампа", "Ванкувер", "Остин", "Солт-Лейк-Сити", "Торонто", "Нэшвилл",
    "Гейнсвилл", "Миннеаполис", "Виннипег", "Бомонт", "Фейетвилл", "Браунсвилл", "Батл-Крик",
    "Гранд-Прери", "Лос-Анджелес", "Джонсборо", "Лас-Вегас", "Калгари", "Буффало", "Ватерлоо", "Дотан",
    "Лаббок", "Виндзор", "Колумбус", "Хьюстон", "Уичито", "Конро", "Янгстаун", "Вашингтон", "Порт-Артур",
    "Роли", "Амарилло", "Кокомо", "Чатем", "Норт-Литл-Рок", "Лонгвью", "Мейкон", "Харлинген", "Киллин",
    "Одесса", "Сан-Диего", "Альбукерке", "Лоутон", "Давенпорт", "Индианаполис", "Сиракузы", "Джоплин", "Ларедо",
    "Монтгомери", "Боулинг Грин", "Лас-Крусес", "Бостон", "Элкхарт", "Джексонвилл", "Талса", "Джексонвилл",
    "Регина", "Новый Орлеан", "Суррей",
    "Огден", "Китченер", "Цинциннати", "Виктория", "Сиэтл", "Боссье Сити",
    "Макаллен", "Сан-Франциско", "Манси", "Конвей", "Роанок", "Тайлер", "Форт Смит", "Бедфорд", "Питтсбург",
    "Салем", "Юма", "Портленд", "Оклахома-Сити", "Ноксвилл", "Ланкастер", "Саскатун", "Шривпорт", "Чико",
    "Эвансвилл", "Берлингтон", "Миссия", "Гранд-Форкс", "Мэдисон", "Палм-Кост", "Викторвилль", "Флинт",
    "Фарр", "Лафайет", "Норфолк", "Гранд-Рапидс", "Денвер", "Кингспорт", "Колорадо-Спрингс", "Оуэнсборо",
    "Темпл", "Энид", "Линкольн", "Кливленд", "Квебек-Сити", "Роки-Маунт", "Орегон-Сити", "Фарго", "Хай-Пойнт",
    "Гвельф", "Паско", "Ричмонд", "Чаттануга", "Модесто", "Палм-Бэй", "Айдахо-Фолс", "Бирмингем",
    "Абботсфорд", "Форт-Уэйн", "Фресно", "Рочестер", "Летбридж", "Олбани", "Майами", "Эшленд", "Ричленд",
    "Скрэнтон", "Уинстон", "Покателло", "Аврора", "Валдоста", "Декейтер", "Палмдейл", "Колумбус", "Роджерс",
    "Рединг", "Виктория", "Гувер", "Гранд-Айленд", "Уичито-Фолс", "Хантсвилл", "Бисмарк", "Чикаго",
    "Джонсон-Сити", "Эдинбург", "Вифлеем", "Пенсакола", "Портервилль", "Сидар-Рапидс", "Батон-Руж", "Пуэбло",
    "Литл-Рок", "Мобил", "Каспер", "Монреаль", "Спрингдейл", "Гесперия", "Вайнленд", "Бикон", " Сент. Облако",
    "Св. Джозеф", "Прово", "Кларксвилл", "Бриджтон", "Окала", "Уэйко", "Окленд", "Терлок", "Кирни",
    "Колумбия", "Рокфорд", "Майнот", "Якима", "Монктон", "Корпус Кристи", "Топика", "Аллентаун", "Лоди",
    "Келоуна", "Де-Мойн", "Терре-Хот", "Кенневик", "Эри", "Хартфорд", "Спрингфилд", "Юба Сити",
    "Провиденс", "Ютика", "Эшвилл", "Бриджпорт", "Барри", "Толедо", "Кеноша", "Дубьюк", "Туларе",
    "О Клэр", "Пеория", "Висалия", "Боулдер", "Фредериктон", "Каса Гранде", "Уокиган", "Лоуренс",
    "Уорнер Робинс", "Эппл Вэлли", "Линчбург", "Мемфис", "Милуоки", "Джейнсвилл", "Ошава", "Бейкерсфилд",
    "Анкоридж", "Шарлотт", "Джексон", "Скоттсдейл", "Рено", "Карсон Сити", "Рочестер", "Медфорд",
    "Гринсборо", "Нормал", "Нанаймо", "Омаха",
    "Су-Фолс", "Биллингс", "Манчестер", "Мантека", "Абилин",
    "Блумингтон", "Мельбурн", "Фэрфилд", "Корваллис", "Хемет", "Хелена", "Шампейн", "Мерсед", "Лексингтон",
    "Нью-Хейвен", "Детройт", "Лансинг", "Бойсе", "Сент-Луис", "Шайенн", "Блумингтон", "Реддинг", "Мэрисвилл",
    "Стоктон",
    "Уилмингтон", "Гринвилл", "Феникс", "Луисвилл", "Фредерик", "Грейт Фоллс", "Эпплтон",
    "Огаста", "Брайан", "Делано", "Миссула", "Брэмптон", "Олимпия", "Юджин", "Форт-Коллинз", "Скенектади",
    "Айова-Сити", "Колледж-Стейшн", "Беллингем", "Гранд-Джанкшн", "Санта-Фе", "Сент. Катаринс", "Андерсон",
    "Лейк Хавасу Сити", "Трейси", "Джолиет", "Логан", "Спокан Вэлли", "Грили", "Орландо", "Спаркс", "Элгин",
    "Форт-Лодердейл", "Филадельфия", "Таллахасси", "Вустер", "Су-Сити", "Ошкош", "Ревелсток",
    "Спокан", "Вирджиния-Бич", "Уэстон", "Бенд", "Ки-Уэст",
    "Харрисонбург", "Оттава", "Рапид Сити", "Сан-Хосе",
    "Коди", "Сакраменто", "Сэндпойнт", "Бельвью", "Манхэттен", "Форт Макмюррей", "Канзас-Сити", "Таос",
    "Уэст-Палм-Бич", "Энн-Арбор", "Пало-Альто", "Дулут", "Нашуа", "Санта-Барбара", "Грин-Бей", "Флагстафф",
    "Галфпорт", "Маунтин-Вью", "Кер д'Ален", "Фэрфакс", "Мидленд", "Чарльстон", "Итака", "Балтимор",
    "Галифакс", "Риверсайд", "Ньюпорт Бич", "Портленд", "Форт Майерс", "Кантон", "Принстон", "Эдмонтон",
    "Стэмфорд", "Лейк Тахо", "Уистлер", "Брентвуд", "Менло Парк", "Порт Сент-Люси", "Окснард", "Индио",
    "Монтерей", "Ла Кросс", "Дейтон", "Плантейшн", "Палм Дезерт", "Сарасота", "Парк Сити", "Галвестон",
    "Брадентон", "Кейп Корал", "Сан-Матео", "Оберн", "Дейтона Бич", "Санта Мария", "Порт-Оранж",
    "Бонита-Спрингс", "Саванна", "Санта-Роза", "Кафедральный город", "Сан-Анджело", "Банф", "Тускалуза", "Ватерлоо",
    "Сент. Джордж", "Петалума", "Энтерпрайз", "Карлсбад", "Сан-Клементе", "Сентенниал", "Лейк Чарльз", "Оушенсайд",
    "Бивертон", "Виста", "Темекула", "Мурриета", "Хендерсон", "Напа", "Верди", "Салем", "Деревня на склоне",
    "Бозман", "Нуук", "Бейрут", "Дубай", "Луксор", "Эль-Гуна", "Гиза", "Каир", "Дахаб", "Александрия", "Амман",
    "Шарджа", "Порт-Саид", "Киркук", "Рамаллах", "Сулеймания", "Духок", "Кум", "Тегеран", "Манама", "Мешхед",
    "Тебриз", "Тель-Авив", "Абу-Даби", "Шираз", "Исфахан", "Хайфа", "Беэр-Шева", "Кувейт-Сити", "Эрбиль", "Доха",
    "Маскат", "Даммам", "Джидда", "Иерусалим", "Эр-Рияд", "Ахваз", "Медина", "Мекка", "Мосул", "Хомс", "Хама",
    "Сана", "Дамаск", "Алеппо", "Басра", "Багдад", "Перт", "Мельбурн", "Сидней", "Окленд", "Гонолулу",
    "Крайстчерч", "Веллингтон", "Сува", "Квинстаун", "Брисбен", "Апиа", "Хагатна", "Нукуалофа", "Данидин",
    "Хобарт", "Аделаида", "Канберра", "Кауаи", "Кэрнс", "Вуллонгонг", "Хило", "Байрон-Бей", "Дарвин", "Ванака",
    "Фунафути", "Дедедо", "Хониара", "Порт-Вила", "Порт-Морсби", "Голд-Кост", "Аваруа", "Нумеа", "Кейптаун",
    "Найроби", "Тагазут", "Порт-Луи", "Кигали", "Йоханнесбург", "Марракеш", "Хараре", "Претория",
    "Порт-Элизабет", "Эль-Джадида", "Лагос", "Ливингстон", "Дакар", "Кампала", "Фес", "Тунис", "Момбаса",
    "Бенин Сити", "Константин", "Кадуна", "Виндхук", "Ибадан", "Агадир", "Танжер", "Рабат", "Дурбан",
    "Касабланка", "Антананариву", "Порт-Харкорт", "Кисангани", "Кумаси", "Бумердас", "Алжир", "Уамбо",
    "Абуджа", "Лубумбаши", "Банжул", "Габороне",
    "Мбужи-Майи", "Кано", "Ломе", "Зария", "Оран", "Дуала",
    "Ниамей", "Эс-Сувейра", "Браззавиль", "Лилонгве", "Фритаун", "Абиджан", "Тебесса", "Соуэто", "Прайя",
    "Конакри", "Кананга", "Луанда", "Уагадугу", "Лусака", "Масеру", "Ямусукро", "Онитша", "Аккра",
    "Эль-Аюн", "Джеймстаун", "Нуакшот", "Яунде", "Киншаса", "Либревиль", "Виктория", "Монровия",
    "Джибути", "Нджамена", "Триполи", "Джуба", "Бенгази", "Хартум", "Банги", "Асмэра", "Мапуту", "Могадишо",
    "Аддис-Абеба", "Бамако", "Дар-эс-Салам", "Ямусукро", "Онитша", "Аккра", "Эль-Аюн", "Джеймстаун",
    "Нуакшот", "Яунде", "Киншаса", "Либревиль", "Виктория", "Монровия", "Джибути", "Нджамена", "Триполи",
    "Джуба", "Бенгази", "Хартум", "Банги", "Асмэра", "Мапуту", "Могадишо", "Аддис-Абеба", "Бамако",
    "Дар-эс-Салам", "Ямусукро", "Онитша", "Аккра", "Эль-Аюн", "Джеймстаун", "Нуакшот", "Яунде",
    "Киншаса", "Либревиль", "Виктория", "Монровия", "Джибути", "Нджамена", "Триполи", "Джуба", "Бенгази",
    "Хартум", "Банги", "Асмэра", "Мапуту", "Могадишо", "Аддис-Абеба", "Бамако", "Дар-эс-Салам", "Бангкок",
    "Чангу", "Чиангмай", "Куала-Лумпур", "Бангалор", "Пенанг", "Ко Пха Нган", "Катманду", "Дананг", "Убуд",
    "Дели", "Хошимин Сити", "Семиньяк", "Манила", "Себу", "Хайдарабад", "Давао", "Сесе", "Сеул", "Хойан",
    "Сиемреап", "Ханой", "Палаван", "Сенггиги", "Фукуок", "Пномпень", "Пусан", "Хайкоу", "Луангпхабанг",
    "Агра", "Покхара", "Краби", "Амритсар", "Джодхпур", "Пхукет", "Джакарта", "Улувату", "Ташкент", "Макати",
    "Генерал Сантос", "Джайпур", "Гуанчжоу", "Гонконг", "Нха Транг", "Майсур", "Кота-Кинабалу", "Тайбэй",
    "Сиаргао", "Мумбаи", "Коломбо", "Галле", "Тайнань", "Гаосюн",
    "Бандунг", "Лакхнау", "Сингапур",
    "Остров Чеджу", "Залив Аругам", "Паттайя", "Чанчжоу", "Джимбаран", "Мадурай", "Гоа", "Нойда", "Амед", "Кучинг",
    "Алматы", "Джамшедпур", "Санур", "Нагпур", "Вишакхапатнам", "Ла Юнион", "Кочи", "Маклеод Гандж", "Канди",
    "Гвалиор", "Сурабая", "Джохор Бару", "Хубли", "Ипох", "Маланг", "Джабалпур", "Лудхиана", "Далат",
    "Аурангабад", "Накхонратчасима", "Кальян", "Кожикоде",
    "Гили Эйр", "Пай", "Матара", "Пеканбару",
    "Ахмадабад", "Чиребон", "Малакка", "Матарам", "Макассар", "Виджаявада", "Ко Ланта", "Лахор", "Алигарх",
    "Канпур", "Варкала", "Чандигарх", "Чианграй", "Хюэ", "Меерут", "Семаранг", "Кота",
    "Вадодара", "Патна",
    "Муйне", "Багио", "Ранчи", "Гургаон", "Тирупур", "Ришикеш", "Читтагонг", "Морадабад", "Тэгу",
    "Самуи", "Медан", "Триссур", "Ко Тао", "Палембанг", "Хуэйчжоу", "Са Па", "Ко Чанг", "Лангкави",
    "Малаппурам", "Наха", "Денпасар", "Гувахати", "Джокьякарта",
    "Суракарта", "Кхулна", "Токио", "Сринагар",
    "Кванджу", "Калькутта", "Варанаси", "Раджкот", "Хуайбэй", "Хуайань", "Хуайнань", "Тэджон", "Гуйян", "Каннур",
    "Коимбаторе", "Дунъин", "Ляньюньган", "Цзинань", "Шаньтоу", "Кута", "Цзямуси", "Дург", "Лючжоу", "Сурат",
    "Васай", "Душанбе", "Коллам", "Сувон", "Чунцин", "Бхубанешвар", "Дунгуань", "Цыси", "Мултан", "Цюаньчжоу",
    "Кинмэнь", "Чаншу", "Бишкек", "Вэйфан", "Си Ань", "Барейли", "Аньянг", "Асансол", "Бахавалпур", "Цзилинь",
    "Астана", "Цзянмэнь", "Гуджранвала", "Ханчжоу", "Наньчан", "Удонтхани", "Чжаньцзян", "Куньмин", "Наньнин",
    "Исламабад", "Карачи", "Хуахин", "Шицзячжуан", "Сиалкот", "Тайчжоу", "Чжуншань", "Шанхай", "Ичан",
    "Кветта", "Чэнду", "Пекин", "Саргодха", "Равалпинди", "Пуна", "Линьи", "Вьентьян", "Зуньи", "Чжэнчжоу",
    "Таншань", "Боракай", "Наньян", "Пешавар", "Бандар Сери Бегаван", "Яншо", "Нинбо", "Тайюань",
    "Синин", "Чжоукоу", "Сянтан", "Яньтай", "Чжучжоу", "Хух-Хото", "Ланьчжоу", "Вэньлин", "Дили", "Фучжоу",
    "Цзыбо", "Нашик", "Фейсалабад", "Шаосин", "Ханьдань", "Ченнаи", "Лоян", "Датун", "Баодин", "Шэньчжэнь",
    "Куньшань", "Тайчжун", "Индор", "Уху", "Сиануквиль", "Нанкин", "Дакка", "Сендай", "Бхопал", "Цицикар",
    "Харбин", "Путянь", "Сюйчжоу", "Ван Вьенг", "Ко Липе", "Чанчунь", "Циньхуандао", "Ао Нанг", "Тан",
    "Наньтун", "Тяньцзинь", "Пхеньян", "Дханбад", "Иньчуань", "Урумчи", "Ко Пхи-Пхи", "Далянь", "Вонсан",
    "Фукуока", "Чжучэн", "Чжухай", "Тируванантапурам",
    "Чжанцзякоу", "Циндао", "Райпур", "Улан-Батор",
    "Чифэн", "Фушунь", "Шэньян", "Ухань", "Цзясин", "Окаяма", "Кэсон", "Кэчхон", "Макао", "Хэфэй",
    "Камияма", "Гуйлинь", "Синуйцзю", "Китакюсю", "Окинава Сити", "Баотоу", "Вэньчжоу", "Танчхон", "Аллахабад",
    "Нагоя", "Убе", "Осака",
    "Жуйань", "Сямынь", "Пунин", "Остров Цусима", "Сучжоу", "Нагасаки", "Янчжоу",
    "Чжанчжоу", "Хамхунг", "Кобе", "Фошань", "Чанша", "Аньшань", "Чонджин", "Иу", "Кагосима",
    "Чжанцзяган", "Киото", "Саривон", "Ашгабат", "Хучжоу", "Нампо", "Сянъян",
    "Мале", "Вэйхай", "Тенчжоу",
    "Доробо", "Саппоро", "Хамамацу", "Хиросима", "Иокогама", "Наго", "Уси", "Томск", "Владивосток",
    "Нейпьидо", "Красноярск", "Омск", "Мандалай", "Новосибирск", "Кабул", "Янгон", "Лиссабон", "Гран-Канария",
    "Тимишоара", "Мадейра", "Портиман", "Лагос",
    "Фуэртевентура", "Эрисейра", "Порту", "Белград", "Берлин",
    "Тенерифе", "Варшава", "Брашов", "Тбилиси", "Варна", "София", "Стамбул", "Лондон", "Клуж", "Вроцлав",
    "Азорские острова", "Будапешт", "Банско", "Майорка", "Дрезден", "Таллинн", "Загреб", "Плоешти", "Пловдив",
    "Бухарест", "Брно", "Краков", "Анталия", "Скопье", "Познань", "Барселона", "Мюнхен", "Щецин", "Задар",
    "Нови Сад", "Констанца", "Мостар", "Любляна", "Алания", "Афины", "Гданьск", "Брага", "Братислава", "Ниш",
    "Ереван", "Гронинген", "Дубровник", "Амстердам", "Фаро", "Адана", "Авейру", "Лейпциг", "Лодзь", "Риека",
    "Крайова", "Рига", "Измир", "Стокгольм", "Приштина", "Аликанте", "Кишинев", "Тирана", "Копенгаген", "Бургас",
    "Франкфурт", "Коимбра", "Сплит", "Менорка", "Валенсия", "Кошице", "Гамбург", "Яссы", "Тампере", "Пафос",
    "Мальме", "Коста-да-Капарика", "Нюрнберг", "Ахен", "Люблин", "Хельсинки", "Анкара", "Монпелье", "Прага",
    "Газиантеп", "Озеро Балатон", "Лейден", "Баня-Лука", "Осиек", "Батуми", "Турку", "Тарту", "Сараево",
    "Катовице", "Осло", "Ньюкасл-апон-Тайн", "Роттердам", "Эдинбург", "Гори", "Гетеборг", "Штутгарт",
    "Хаген", "Лилль", "Карлсруэ", "Бирмингем", "Бат", "Оулу", "Йена", "Каунас", "Абердин", "Дублин",
    "Подгорица", "Грац", "Бремен", "Инсбрук", "Ханья", "Тулуза", "Ноттингем", "Лион", "Цюрих", "Кельн",
    "Баку", "Лестер", "Вильнюс", "Ковентри", "Вена", "Рейкьявик", "Рединг", "Лутон", "Женева", "Ницца",
    "Бодрум", "Мадрид", "Клайпеда", "Манчестер", "Нортгемптон", "Будва", "Жешув", "Борнмут", "Конья",
    "Ювяскюля", "Венеция", "Портсмут", "Глазго", "Никосия", "Гейдельберг", "Патры", "Эспоо", "Палермо",
    "Лимассол", "Шумперк", "Бристоль", "Ренн", "Дортмунд", "Билефельд", "Цавтат", "Ла-Корунья", "Париж",
    "Гаага", "Неймеген", "Салоники", "Лидс", "Утрехт", "Гент", "Озеро Комо", "Брюссель", "Памплона",
    "Ливерпуль", "Бреда", "Малага", "Хаддерсфилд", "Севилья", "Нант", "Оксфорд", "Котор", "Корк", "Орхус",
    "Хоф", "Саутгемптон", "Ганновер", "Берн", "Голуэй", "Рим", "Гранада",
    "Кассель", "Марбелья", "Гренобль",
    "Хвар", "Эйндховен", "Страсбург", "Хавеа", "Флоренция", "Кардифф", "Ольборг", "Халл", "Йорк", "Кембридж",
    "Зволле", "Антверпен", "Бар", "Норвич", "Схевенинген", "Милан", "Эрланген", "Тилбург", "Марсель", "Родос",
    "Левен", "Зандворт", "Шеффилд", "Компорта", "Падуя", "Монако", "Челтнем", "Девентер", "Тронхейм",
    "Арнем", "Шрусбери", "Ларнака", "Леуварден", "Лелистад", "Лансароте", "Берген", "Харлем", "Тромсе",
    "Тексель", "Неаполь", "Бордо", "Триест", "Канны", "Брюгге", "Мамайя", "Лугано", "Пиза", "Гибралтар",
    "Шамони", "Сан-Себастьян", "Слима", "Базель", "Андорра-ла-Велья", "Алмере", "Дармштадт", "Сент-Хелиер",
    "Анси", "Люксембург", "Ибица", "Болонья", "Тренто", "Лозанна", "Бурса", "Зальцбург", "Арендал", "Биарриц",
    "Модена", "Дюссельдорф", "Генуя", "Олесунн", "Ретимно", "Торсхавн", "Брайтон", "Интерлакен", "Рованиеми",
    "Дижон", "Санторини", "Миконос", "Трир", "Св. Галлен", "Кордова", "Кальяри", "Авеллино", "Тревизо",
    "Тарифа", "Феррара", "Римини", "Верона", "Бильбао", "Руан", "Лукка", "Белфаст", "Амальфи", "Авиньон", "Бари",
    "Монца", "Ватикан", "Турин", "Сиена", "Аяччо", "Эксетер", "Обнинск", "Новочеркасск", "Ивано-Франковск",
    "Сочи", "Калининград", "Ульяновск", "Ижевск", "Кривой Рог", "Львов", "Краснодар", "Саратов", "Днепр",
    "Одесса", "Волгоград", "Уфа", "Ростов-на-Дону", "Челябинск", "Казань", "Самара", "Нижний", "Харьков",
    "Екатеринбург", "Минск", "Киев", "Санкт-Петербург", "Москва", "Штутгарт", "Иннополис", "Тюмень", "Владимир"
]

cities_ru_to_eng = {'Буэнос-Айрес': 'Buenos Aires', 'Мехико': 'Mexico City', 'Медельин': 'Medellín',
                    'Гвадалахара': 'Guadalajara', 'Лима': 'Lima', 'Куэнка': 'Cuenca', 'Гавана': 'Havana',
                    'Сан-Паулу': 'São Paulo', 'Рио-де-Жанейро': 'Rio de Janeiro', 'Оахака': 'Oaxaca',
                    'Канкун': 'Cancun', 'Галапагосские острова': 'Galapagos Islands', 'Флорианополис': 'Florianopolis',
                    ' Керетаро': 'Queretaro', 'Кордова': 'Cordoba', 'Сантьяго': 'Santiago',
                    'Пуэрто-Эскондидо': 'Puerto Escondido', 'Порту-Алегри': 'Porto Alegre', 'Монтеррей': 'Monterrey',
                    'Белу-Оризонти': 'Belo Horizonte', 'Парамарибо': 'Paramaribo', 'Антигуа': 'Antigua',
                    'Мерида': 'Merida', 'Росарио': 'Rosario', 'Кито': 'Quito', 'Плайя-дель-Кармен': 'Playa del Carmen',
                    'Богота': 'Bogota', 'Асунсьон': 'Asuncion', 'Виллемстад': 'Willemstad', 'Форталеза': 'Fortaleza',
                    'Наталь': 'Natal', 'Картахена': 'Cartagena', 'Ла-Пас': 'La Paz', 'Гуанахуато': 'Guanajuato',
                    'Минка': 'Minca', 'Арекипа': 'Arequipa', 'Санта-Крус': 'Santa Cruz', 'Сан-Хосе': 'San Jose',
                    'Гояния': 'Goiania', 'Эрмосильо': 'Hermosillo', 'Санто-Доминго': 'Santo Domingo',
                    'Куритиба': 'Curitiba', 'Панама-Сити': 'Panama City',
                    'Сан-Мигель-де-Альенде': 'San Miguel de Allende', 'Ла-Серена': 'La Serena', 'Сан-Хуан': 'San Juan',
                    'Кочабамба': 'Cochabamba', 'Сальта': 'Salta', 'Мендоса': 'Mendoza', 'Тихуана': 'Tijuana',
                    'Белем': 'Belem', 'Интаг Вэлли': 'Intag Valley', 'Эль-Альто': 'El Alto', 'Куско': 'Cusco',
                    'Ушуайя': 'Ushuaia', 'Кампинас': 'Campinas', 'Гуаякиль': 'Guayaquil',
                    'Мар-дель-Плата': 'Mar del Plata', 'Толука': 'Toluca', 'Уберландия': 'Uberlandia',
                    'Букараманга': 'Bucaramanga', 'Гватемала Сити': 'Guatemala City', 'Ресифи': 'Recife',
                    'Сан-Луис-Потоси': 'San Luis Potosi', 'Чачапояс': 'Chachapoyas', 'Пасто': 'Pasto', 'Кали': 'Cali',
                    'Пуэбла': 'Puebla', 'Монтевидео': 'Montevideo', 'Кампус-дус-Гойтаказес': 'Campos dos Goytacazes',
                    'Саленто': 'Salento', 'Сан-Луис': 'Sao Luis', 'Леон': 'León', 'Либерия': 'Liberia',
                    'Сальвадор': 'Salvador', 'Сан-Кристобаль-де-лас-Касас': 'San Cristóbal de las Casas',
                    'Бразилиа': 'Brasilia', 'Барранкилья': 'Barranquilla', 'Сан-Жозе-дус-Кампус': 'São José dos Campos',
                    'Тулум': 'Tulum', 'Итапема': 'Itapema', 'Витория': 'Vitória', 'Порт-о-Пренс': 'Port-au-Prince',
                    'Косумель': 'Cozumel', 'Маракайбо': 'Maracaibo', 'Сан-Хуан-дель-Сур': 'San Juan del Sur',
                    'Панахачель': 'Panajachel', 'Хуарес': 'Juarez', 'Кампо Гранде': 'Campo Grande',
                    'Ла Плата': 'La Plata', 'Манагуа': 'Managua', 'Аннаполис': 'Anápolis', 'Джорджтаун': 'George Town',
                    'Кабарете': 'Cabarete', 'Маракай': 'Maracay', 'Санта-Марта': 'Santa Marta',
                    'Кей Колкер': 'Caye Caulker', 'Сорокаба': 'Sorocaba', 'Вальпараисо': 'Valparaíso',
                    'Кингстон': 'Kingston', 'Пуэрто-Вальярта': 'Puerto Vallarta', 'Сан-Сальвадор': 'San Salvador',
                    'Мехикали': 'Mexicali', 'Тегусигальпа': 'Tegucigalpa', 'Торреон': 'Torreon',
                    'Бокас-дель-Торо': 'Bocas del Toro', 'Ораньестад': 'Oranjestad', 'Жоао Песоа': 'Joao Pessoa',
                    'Монтанита': 'Montanita', 'Пуэрто-Вьехо': 'Puerto Viejo', ' Белиз Город': 'Belize City',
                    'Джундиаи': 'Jundiaí', 'Манаус': 'Manaus', 'Сан-Педро-Сула': 'San Pedro Sula', 'Каракас': 'Caracas',
                    'Саюлита': 'Sayulita', 'Санта-Тереза': 'Santa Teresa', 'Икике': 'Iquique',
                    'Сан-Игнасио': 'San Ignacio', 'Агуаскальентес': 'Aguascalientes', 'Копан': 'Copan',
                    'Харабакоа': 'Jarabacoa', 'Роуд-Таун': 'Road Town', 'Манкора': 'Mancora',
                    'Порт-оф-Спейн': 'Port of Spain', 'Пунта-дель-Эсте': 'Punta del Este',
                    'Винья-дель-Мар': 'Viña del Mar', 'Стэнли': 'Stanley', 'Монтего-Бей': 'Montego Bay',
                    'Нассау': 'Nassau', 'Гамильтон': 'Hamilton', 'Антофагаста': 'Antofagasta',
                    'Кралендейк': 'Kralendijk', 'Шарлотта Амалия': 'Charlotte Amalie', 'Филипсбург': 'Philipsburg',
                    'Бас-Терре': 'Basse-Terre', 'Бриджтаун': 'Bridgetown', 'Кинг-Эдвард-Пойнт': 'King Edward Point',
                    'Острова залива': 'Bay Islands', 'Сент-Джонс': "St John's", 'Кайенна': 'Cayenne',
                    'Тамаринд': 'Tamarindo', 'Сан-Педро-де-Атакама': 'San Pedro de Atacama', 'Сан-Педро': 'San Pedro',
                    'Исла-Мухерес': 'Isla Mujeres', 'Мартиника': 'Martinique', 'Пунта-Кана': 'Punta Cana',
                    'Кабо-Сан-Лукас': 'Cabo San Lucas', 'Табарана-ду-Норте': 'Tabaranã do Norte',
                    'Сан-Антонио': 'San Antonio', 'Атланта': 'Atlanta', 'Даллас': 'Dallas', 'Нью-Йорк': 'New York City',
                    'Тусон': 'Tucson', 'Тампа': 'Tampa', 'Ванкувер': 'Vancouver', 'Остин': 'Austin',
                    'Солт-Лейк-Сити': 'Salt Lake City', 'Торонто': 'Toronto', 'Нэшвилл': 'Nashville',
                    'Гейнсвилл': 'Gainesville', 'Миннеаполис': 'Minneapolis', 'Виннипег': 'Winnipeg',
                    'Бомонт': 'Beaumont', 'Фейетвилл': 'Fayetteville', 'Браунсвилл': 'Brownsville',
                    'Батл-Крик': 'Battle Creek', 'Гранд-Прери': 'Grande Prairie', 'Лос-Анджелес': 'Los Angeles',
                    'Джонсборо': 'Jonesboro', 'Лас-Вегас': 'Las Vegas', 'Калгари': 'Calgary', 'Буффало': 'Buffalo',
                    'Ватерлоо': 'Waterloo', 'Дотан': 'Dothan', 'Лаббок': 'Lubbock', 'Виндзор': 'Windsor',
                    'Колумбус': 'Columbus', 'Хьюстон': 'Houston', 'Уичито': 'Wichita', 'Конро': 'Conroe',
                    'Янгстаун': 'Youngstown', 'Вашингтон': 'Washington', 'Порт-Артур': 'Port Arthur', 'Роли': 'Raleigh',
                    'Амарилло': 'Amarillo', 'Кокомо': 'Kokomo', 'Чатем': 'Chatham',
                    'Норт-Литл-Рок': 'North Little Rock', 'Лонгвью': 'Longview', 'Мейкон': 'Macon',
                    'Харлинген': 'Harlingen', 'Киллин': 'Killeen', 'Одесса': 'Odessa', 'Сан-Диего': 'San Diego',
                    'Альбукерке': 'Albuquerque', 'Лоутон': 'Lawton', 'Давенпорт': 'Davenport',
                    'Индианаполис': 'Indianapolis', 'Сиракузы': 'Syracuse', 'Джоплин': 'Joplin', 'Ларедо': 'Laredo',
                    'Монтгомери': 'Montgomery', 'Боулинг Грин': 'Bowling Green', 'Лас-Крусес': 'Las Cruces',
                    'Бостон': 'Boston', 'Элкхарт': 'Elkhart', 'Джексонвилл': 'Jacksonville', 'Талса': 'Tulsa',
                    'Регина': 'Regina', 'Новый Орлеан': 'New Orleans', 'Суррей': 'Surrey', 'Огден': 'Ogden',
                    'Китченер': 'Kitchener', 'Цинциннати': 'Cincinnati', 'Виктория': 'Victoria', 'Сиэтл': 'Seattle',
                    'Боссье Сити': 'Bossier City', 'Макаллен': 'McAllen', 'Сан-Франциско': 'San Francisco',
                    'Манси': 'Muncie', 'Конвей': 'Conway', 'Роанок': 'Roanoke', 'Тайлер': 'Tyler',
                    'Форт Смит': 'Fort Smith', 'Бедфорд': 'Bedford', 'Питтсбург': 'Pittsburgh', 'Салем': 'Salem',
                    'Юма': 'Yuma', 'Портленд': 'Portland', 'Оклахома-Сити': 'Oklahoma City', 'Ноксвилл': 'Knoxville',
                    'Ланкастер': 'Lancaster', 'Саскатун': 'Saskatoon', 'Шривпорт': 'Shreveport', 'Чико': 'Chico',
                    'Эвансвилл': 'Evansville', 'Берлингтон': 'Burlington', 'Миссия': 'Mission',
                    'Гранд-Форкс': 'Grand Forks', 'Мэдисон': 'Madison', 'Палм-Кост': 'Palm Coast',
                    'Викторвилль': 'Victorville', 'Флинт': 'Flint', 'Фарр': 'Pharr', 'Лафайет': 'Lafayette',
                    'Норфолк': 'Norfolk', 'Гранд-Рапидс': 'Grand Rapids', 'Денвер': 'Denver', 'Кингспорт': 'Kingsport',
                    'Колорадо-Спрингс': 'Colorado Springs', 'Оуэнсборо': 'Owensboro', 'Темпл': 'Temple', 'Энид': 'Enid',
                    'Линкольн': 'Lincoln', 'Кливленд': 'Cleveland', 'Квебек-Сити': 'Quebec City',
                    'Роки-Маунт': 'Rocky Mount', 'Орегон-Сити': 'Oregon City', 'Фарго': 'Fargo',
                    'Хай-Пойнт': 'High Point', 'Гвельф': 'Guelph', 'Паско': 'Pasco', 'Ричмонд': 'Richmond',
                    'Чаттануга': 'Chattanooga', 'Модесто': 'Modesto', 'Палм-Бэй': 'Palm Bay',
                    'Айдахо-Фолс': 'Idaho Falls', 'Бирмингем': 'Birmingham', 'Абботсфорд': 'Abbotsford',
                    'Форт-Уэйн': 'Fort Wayne', 'Фресно': 'Fresno', 'Рочестер': 'Rochester', 'Летбридж': 'Lethbridge',
                    'Олбани': 'Albany', 'Майами': 'Miami', 'Эшленд': 'Ashland', 'Ричленд': 'Richland',
                    'Скрэнтон': 'Scranton', 'Уинстон': 'Winston', 'Покателло': 'Pocatello', 'Аврора': 'Aurora',
                    'Валдоста': 'Valdosta', 'Декейтер': 'Decatur', 'Палмдейл': 'Palmdale', 'Роджерс': 'Rogers',
                    'Рединг': 'Reading', 'Гувер': 'Hoover', 'Гранд-Айленд': 'Grand Island',
                    'Уичито-Фолс': 'Wichita Falls', 'Хантсвилл': 'Huntsville', 'Бисмарк': 'Bismarck',
                    'Чикаго': 'Chicago', 'Джонсон-Сити': 'Johnson City', 'Эдинбург': 'Edinburgh',
                    'Вифлеем': 'Bethlehem', 'Пенсакола': 'Pensacola', 'Портервилль': 'Porterville',
                    'Сидар-Рапидс': 'Cedar Rapids', 'Батон-Руж': 'Baton Rouge', 'Пуэбло': 'Pueblo',
                    'Литл-Рок': 'Little Rock', 'Мобил': 'Mobile', 'Каспер': 'Casper', 'Монреаль': 'Montreal',
                    'Спрингдейл': 'Springdale', 'Гесперия': 'Hesperia', 'Вайнленд': 'Vineland', 'Бикон': 'Beacon',
                    ' Сент. Облако': 'St. Cloud', 'Св. Джозеф': 'St. Joseph', 'Прово': 'Provo',
                    'Кларксвилл': 'Clarksville', 'Бриджтон': 'Bridgeton', 'Окала': 'Ocala', 'Уэйко': 'Waco',
                    'Окленд': 'Auckland', 'Терлок': 'Turlock', 'Кирни': 'Kearney', 'Колумбия': 'Columbia',
                    'Рокфорд': 'Rockford', 'Майнот': 'Minot', 'Якима': 'Yakima', 'Монктон': 'Moncton',
                    'Корпус Кристи': 'Corpus Christi', 'Топика': 'Topeka', 'Аллентаун': 'Allentown', 'Лоди': 'Lodi',
                    'Келоуна': 'Kelowna', 'Де-Мойн': 'Des Moines', 'Терре-Хот': 'Terre Haute', 'Кенневик': 'Kennewick',
                    'Эри': 'Erie', 'Хартфорд': 'Hartford', 'Спрингфилд': 'Springfield', 'Юба Сити': 'Yuba City',
                    'Провиденс': 'Providence', 'Ютика': 'Utica', 'Эшвилл': 'Asheville', 'Бриджпорт': 'Bridgeport',
                    'Барри': 'Barrie', 'Толедо': 'Toledo', 'Кеноша': 'Kenosha', 'Дубьюк': 'Dubuque', 'Туларе': 'Tulare',
                    'О Клэр': 'Eau Claire', 'Пеория': 'Peoria', 'Висалия': 'Visalia', 'Боулдер': 'Boulder',
                    'Фредериктон': 'Fredericton', 'Каса Гранде': 'Casa Grande', 'Уокиган': 'Waukegan',
                    'Лоуренс': 'Lawrence', 'Уорнер Робинс': 'Warner Robins', 'Эппл Вэлли': 'Apple Valley',
                    'Линчбург': 'Lynchburg', 'Мемфис': 'Memphis', 'Милуоки': 'Milwaukee', 'Джейнсвилл': 'Janesville',
                    'Ошава': 'Oshawa', 'Бейкерсфилд': 'Bakersfield', 'Анкоридж': 'Anchorage', 'Шарлотт': 'Charlotte',
                    'Джексон': 'Jackson', 'Скоттсдейл': 'Scottsdale', 'Рено': 'Reno', 'Карсон Сити': 'Carson City',
                    'Медфорд': 'Medford', 'Гринсборо': 'Greensboro', 'Нормал': 'Normal', 'Нанаймо': 'Nanaimo',
                    'Омаха': 'Omaha', 'Су-Фолс': 'Sioux Falls', 'Биллингс': 'Billings', 'Манчестер': 'Manchester',
                    'Мантека': 'Manteca', 'Абилин': 'Abilene', 'Блумингтон': 'Bloomington', 'Мельбурн': 'Melbourne',
                    'Фэрфилд': 'Fairfield', 'Корваллис': 'Corvallis', 'Хемет': 'Hemet', 'Хелена': 'Helena',
                    'Шампейн': 'Champaign', 'Мерсед': 'Merced', 'Лексингтон': 'Lexington', 'Нью-Хейвен': 'New Haven',
                    'Детройт': 'Detroit', 'Лансинг': 'Lansing', 'Бойсе': 'Boise', 'Сент-Луис': 'St. Louis',
                    'Шайенн': 'Cheyenne', 'Реддинг': 'Redding', 'Мэрисвилл': 'Marysville', 'Стоктон': 'Stockton',
                    'Уилмингтон': 'Wilmington', 'Гринвилл': 'Greenville', 'Феникс': 'Phoenix', 'Луисвилл': 'Louisville',
                    'Фредерик': 'Frederick', 'Грейт Фоллс': 'Great Falls', 'Эпплтон': 'Appleton', 'Огаста': 'Augusta',
                    'Брайан': 'Bryan', 'Делано': 'Delano', 'Миссула': 'Missoula', 'Брэмптон': 'Brampton',
                    'Олимпия': 'Olympia', 'Юджин': 'Eugene', 'Форт-Коллинз': 'Fort Collins',
                    'Скенектади': 'Schenectady', 'Айова-Сити': 'Iowa City', 'Колледж-Стейшн': 'College Station',
                    'Беллингем': 'Bellingham', 'Гранд-Джанкшн': 'Grand Junction', 'Санта-Фе': 'Santa Fe',
                    'Сент. Катаринс': 'St. Catharines', 'Андерсон': 'Anderson', 'Лейк Хавасу Сити': 'Lake Havasu City',
                    'Трейси': 'Tracy', 'Джолиет': 'Joliet', 'Логан': 'Logan', 'Спокан Вэлли': 'Spokane Valley',
                    'Грили': 'Greeley', 'Орландо': 'Orlando', 'Спаркс': 'Sparks', 'Элгин': 'Elgin',
                    'Форт-Лодердейл': 'Fort Lauderdale', 'Филадельфия': 'Philadelphia', 'Таллахасси': 'Tallahassee',
                    'Вустер': 'Worcester', 'Су-Сити': 'Sioux City', 'Ошкош': 'Oshkosh', 'Ревелсток': 'Revelstoke',
                    'Спокан': 'Spokane', 'Вирджиния-Бич': 'Virginia Beach', 'Уэстон': 'Weston', 'Бенд': 'Bend',
                    'Ки-Уэст': 'Key West', 'Харрисонбург': 'Harrisonburg', 'Оттава': 'Ottawa',
                    'Рапид Сити': 'Rapid City', 'Коди': 'Cody', 'Сакраменто': 'Sacramento', 'Сэндпойнт': 'Sandpoint',
                    'Бельвью': 'Bellevue', 'Манхэттен': 'Manhattan', 'Форт Макмюррей': 'Fort McMurray',
                    'Канзас-Сити': 'Kansas City', 'Таос': 'Taos', 'Уэст-Палм-Бич': 'West Palm Beach',
                    'Энн-Арбор': 'Ann Arbor', 'Пало-Альто': 'Palo Alto', 'Дулут': 'Duluth', 'Нашуа': 'Nashua',
                    'Санта-Барбара': 'Santa Barbara', 'Грин-Бей': 'Green Bay', 'Флагстафф': 'Flagstaff',
                    'Галфпорт': 'Gulfport', 'Маунтин-Вью': 'Mountain View', "Кер д'Ален": "Coeur d'Alene",
                    'Фэрфакс': 'Fairfax', 'Мидленд': 'Midland', 'Чарльстон': 'Charleston', 'Итака': 'Ithaca',
                    'Балтимор': 'Baltimore', 'Галифакс': 'Halifax', 'Риверсайд': 'Riverside',
                    'Ньюпорт Бич': 'Newport Beach', 'Форт Майерс': 'Fort Myers', 'Кантон': 'Canton',
                    'Принстон': 'Princeton', 'Эдмонтон': 'Edmonton', 'Стэмфорд': 'Stamford', 'Лейк Тахо': 'Lake Tahoe',
                    'Уистлер': 'Whistler', 'Брентвуд': 'Brentwood', 'Менло Парк': 'Menlo Park',
                    'Порт Сент-Люси': 'Port St. Lucie', 'Окснард': 'Oxnard', 'Индио': 'Indio', 'Монтерей': 'Monterey',
                    'Ла Кросс': 'La Crosse', 'Дейтон': 'Dayton', 'Плантейшн': 'Plantation',
                    'Палм Дезерт': 'Palm Desert', 'Сарасота': 'Sarasota', 'Парк Сити': 'Park City',
                    'Галвестон': 'Galveston', 'Брадентон': 'Bradenton', 'Кейп Корал': 'Cape Coral',
                    'Сан-Матео': 'San Mateo', 'Оберн': 'Auburn', 'Дейтона Бич': 'Daytona Beach',
                    'Санта Мария': 'Santa Maria', 'Порт-Оранж': 'Port Orange', 'Бонита-Спрингс': 'Bonita Springs',
                    'Саванна': 'Savannah', 'Санта-Роза': 'Santa Rosa', 'Кафедральный город': 'Cathedral City',
                    'Сан-Анджело': 'San Angelo', 'Банф': 'Banff', 'Тускалуза': 'Tuscaloosa',
                    'Сент. Джордж': 'St. George', 'Петалума': 'Petaluma', 'Энтерпрайз': 'Enterprise',
                    'Карлсбад': 'Carlsbad', 'Сан-Клементе': 'San Clemente', 'Сентенниал': 'Centennial',
                    'Лейк Чарльз': 'Lake Charles', 'Оушенсайд': 'Oceanside', 'Бивертон': 'Beaverton', 'Виста': 'Vista',
                    'Темекула': 'Temecula', 'Мурриета': 'Murrieta', 'Хендерсон': 'Henderson', 'Напа': 'Napa',
                    'Верди': 'Verdi', 'Деревня на склоне': 'Incline Village', 'Бозман': 'Bozeman', 'Нуук': 'Nuuk',
                    'Бейрут': 'Beirut', 'Дубай': 'Dubai', 'Луксор': 'Luxor', 'Эль-Гуна': 'El Gouna', 'Гиза': 'Giza',
                    'Каир': 'Cairo', 'Дахаб': 'Dahab', 'Александрия': 'Alexandria', 'Амман': 'Amman',
                    'Шарджа': 'Sharjah', 'Порт-Саид': 'Port Said', 'Киркук': 'Kirkuk', 'Рамаллах': 'Ramallah',
                    'Сулеймания': 'Sulaymaniyah', 'Духок': 'Duhok', 'Кум': 'Qom', 'Тегеран': 'Tehran',
                    'Манама': 'Manama', 'Мешхед': 'Mashhad', 'Тебриз': 'Tabriz', 'Тель-Авив': 'Tel Aviv',
                    'Абу-Даби': 'Abu Dhabi', 'Шираз': 'Shiraz', 'Исфахан': 'Isfahan', 'Хайфа': 'Haifa',
                    'Беэр-Шева': 'Beersheba', 'Кувейт-Сити': 'Kuwait City', 'Эрбиль': 'Erbil', 'Доха': 'Doha',
                    'Маскат': 'Muscat', 'Даммам': 'Dammam', 'Джидда': 'Jeddah', 'Иерусалим': 'Jerusalem',
                    'Эр-Рияд': 'Riyadh', 'Ахваз': 'Ahvaz', 'Медина': 'Medina', 'Мекка': 'Mecca', 'Мосул': 'Mosul',
                    'Хомс': 'Homs', 'Хама': 'Hama', 'Сана': "Sana'a", 'Дамаск': 'Damascus', 'Алеппо': 'Aleppo',
                    'Басра': 'Basra', 'Багдад': 'Baghdad', 'Перт': 'Perth', 'Сидней': 'Sydney', 'Гонолулу': 'Honolulu',
                    'Крайстчерч': 'Christchurch', 'Веллингтон': 'Wellington', 'Сува': 'Suva', 'Квинстаун': 'Queenstown',
                    'Брисбен': 'Brisbane', 'Апиа': 'Apia', 'Хагатна': 'Hagatna', 'Нукуалофа': "Nuku'alofa",
                    'Данидин': 'Dunedin', 'Хобарт': 'Hobart', 'Аделаида': 'Adelaide', 'Канберра': 'Canberra',
                    'Кауаи': 'Kauai', 'Кэрнс': 'Cairns', 'Вуллонгонг': 'Wollongong', 'Хило': 'Hilo',
                    'Байрон-Бей': 'Byron Bay', 'Дарвин': 'Darwin', 'Ванака': 'Wanaka', 'Фунафути': 'Funafuti',
                    'Дедедо': 'Dededo', 'Хониара': 'Honiara', 'Порт-Вила': 'Port Vila', 'Порт-Морсби': 'Port Moresby',
                    'Голд-Кост': 'Gold Coast', 'Аваруа': 'Avarua', 'Нумеа': 'Nouméa', 'Кейптаун': 'Cape Town',
                    'Найроби': 'Nairobi', 'Тагазут': 'Taghazout', 'Порт-Луи': 'Port Louis', 'Кигали': 'Kigali',
                    'Йоханнесбург': 'Johannesburg', 'Марракеш': 'Marrakesh', 'Хараре': 'Harare', 'Претория': 'Pretoria',
                    'Порт-Элизабет': 'Port Elizabeth', 'Эль-Джадида': 'El Jadida', 'Лагос': 'Lagos',
                    'Ливингстон': 'Livingstone', 'Дакар': 'Dakar', 'Кампала': 'Kampala', 'Фес': 'Fes', 'Тунис': 'Tunis',
                    'Момбаса': 'Mombasa', 'Бенин Сити': 'Benin City', 'Константин': 'Constantine', 'Кадуна': 'Kaduna',
                    'Виндхук': 'Windhoek', 'Ибадан': 'Ibadan', 'Агадир': 'Agadir', 'Танжер': 'Tangier',
                    'Рабат': 'Rabat', 'Дурбан': 'Durban', 'Касабланка': 'Casablanca', 'Антананариву': 'Antananarivo',
                    'Порт-Харкорт': 'Port Harcourt', 'Кисангани': 'Kisangani', 'Кумаси': 'Kumasi',
                    'Бумердас': 'Boumerdas', 'Алжир': 'Algiers', 'Уамбо': 'Huambo', 'Абуджа': 'Abuja',
                    'Лубумбаши': 'Lubumbashi', 'Банжул': 'Banjul', 'Габороне': 'Gaborone', 'Мбужи-Майи': 'Mbuji-Mayi',
                    'Кано': 'Kano', 'Ломе': 'Lome', 'Зария': 'Zaria', 'Оран': 'Oran', 'Дуала': 'Douala',
                    'Ниамей': 'Niamey', 'Эс-Сувейра': 'Essaouira', 'Браззавиль': 'Brazzaville', 'Лилонгве': 'Lilongwe',
                    'Фритаун': 'Freetown', 'Абиджан': 'Abidjan', 'Тебесса': 'Tebessa', 'Соуэто': 'Soweto',
                    'Прайя': 'Praia', 'Конакри': 'Conakry', 'Кананга': 'Kananga', 'Луанда': 'Luanda',
                    'Уагадугу': 'Ouagadougou', 'Лусака': 'Lusaka', 'Масеру': 'Maseru', 'Ямусукро': 'Yamoussoukro',
                    'Онитша': 'Onitsha', 'Аккра': 'Accra', 'Эль-Аюн': 'Laayoune', 'Джеймстаун': 'Jamestown',
                    'Нуакшот': 'Nouakchott', 'Яунде': 'Yaounde', 'Киншаса': 'Kinshasa', 'Либревиль': 'Libreville',
                    'Монровия': 'Monrovia', 'Джибути': 'Djibouti', 'Нджамена': "N'Djamena", 'Триполи': 'Tripoli',
                    'Джуба': 'Juba', 'Бенгази': 'Benghazi', 'Хартум': 'Khartoum', 'Банги': 'Bangui', 'Асмэра': 'Asmara',
                    'Мапуту': 'Maputo', 'Могадишо': 'Mogadishu', 'Аддис-Абеба': 'Addis Ababa', 'Бамако': 'Bamako',
                    'Дар-эс-Салам': 'Dar es Salaam', 'Бангкок': 'Bangkok', 'Чангу': 'Canggu', 'Чиангмай': 'Chiang Mai',
                    'Куала-Лумпур': 'Kuala Lumpur', 'Бангалор': 'Bengaluru', 'Пенанг': 'Penang',
                    'Ко Пха Нган': 'Ko Pha Ngan', 'Катманду': 'Kathmandu', 'Дананг': 'Da Nang', 'Убуд': 'Ubud',
                    'Дели': 'Delhi', 'Хошимин Сити': 'Ho Chi Minh City', 'Семиньяк': 'Seminyak', 'Манила': 'Manila',
                    'Себу': 'Cebu', 'Хайдарабад': 'Hyderabad', 'Давао': 'Davao', 'Сесе': 'Seseh', 'Сеул': 'Seoul',
                    'Хойан': 'Hoi An', 'Сиемреап': 'Siem Reap', 'Ханой': 'Hanoi', 'Палаван': 'Palawan',
                    'Сенггиги': 'Senggigi', 'Фукуок': 'Phu Quoc', 'Пномпень': 'Phnom Penh', 'Пусан': 'Busan',
                    'Хайкоу': 'Haikou', 'Луангпхабанг': 'Luang Prabang', 'Агра': 'Agra', 'Покхара': 'Pokhara',
                    'Краби': 'Krabi', 'Амритсар': 'Amritsar', 'Джодхпур': 'Jodhpur', 'Пхукет': 'Phuket',
                    'Джакарта': 'Jakarta', 'Улувату': 'Uluwatu', 'Ташкент': 'Tashkent', 'Макати': 'Makati',
                    'Генерал Сантос': 'General Santos', 'Джайпур': 'Jaipur', 'Гуанчжоу': 'Guangzhou',
                    'Гонконг': 'Hong Kong', 'Нха Транг': 'Nha Trang', 'Майсур': 'Mysore',
                    'Кота-Кинабалу': 'Kota Kinabalu', 'Тайбэй': 'Taipei', 'Сиаргао': 'Siargao', 'Мумбаи': 'Mumbai',
                    'Коломбо': 'Colombo', 'Галле': 'Galle', 'Тайнань': 'Tainan', 'Гаосюн': 'Kaohsiung',
                    'Бандунг': 'Bandung', 'Лакхнау': 'Lucknow', 'Сингапур': 'Singapore', 'Остров Чеджу': 'Jeju Island',
                    'Залив Аругам': 'Arugam Bay', 'Паттайя': 'Pattaya', 'Чанчжоу': 'Changzhou', 'Джимбаран': 'Jimbaran',
                    'Мадурай': 'Madurai', 'Гоа': 'Goa', 'Нойда': 'Noida', 'Амед': 'Amed', 'Кучинг': 'Kuching',
                    'Алматы': 'Almaty', 'Джамшедпур': 'Jamshedpur', 'Санур': 'Sanur', 'Нагпур': 'Nagpur',
                    'Вишакхапатнам': 'Visakhapatnam', 'Ла Юнион': 'La Union', 'Кочи': 'Kochi',
                    'Маклеод Гандж': 'McLeod Ganj', 'Канди': 'Kandy', 'Гвалиор': 'Gwalior', 'Сурабая': 'Surabaya',
                    'Джохор Бару': 'Johor Bahru', 'Хубли': 'Hubli', 'Ипох': 'Ipoh', 'Маланг': 'Malang',
                    'Джабалпур': 'Jabalpur', 'Лудхиана': 'Ludhiana', 'Далат': 'Da Lat', 'Аурангабад': 'Aurangabad',
                    'Накхонратчасима': 'Nakhon Ratchasima', 'Кальян': 'Kalyan', 'Кожикоде': 'Kozhikode',
                    'Гили Эйр': 'Gili Air', 'Пай': 'Pai', 'Матара': 'Matara', 'Пеканбару': 'Pekanbaru',
                    'Ахмадабад': 'Ahmedabad', 'Чиребон': 'Cirebon', 'Малакка': 'Malacca', 'Матарам': 'Mataram',
                    'Макассар': 'Makassar', 'Виджаявада': 'Vijayawada', 'Ко Ланта': 'Ko Lanta', 'Лахор': 'Lahore',
                    'Алигарх': 'Aligarh', 'Канпур': 'Kanpur', 'Варкала': 'Varkala', 'Чандигарх': 'Chandigarh',
                    'Чианграй': 'Chiang Rai', 'Хюэ': 'Hue', 'Меерут': 'Meerut', 'Семаранг': 'Semarang', 'Кота': 'Kota',
                    'Вадодара': 'Vadodara', 'Патна': 'Patna', 'Муйне': 'Mui Ne', 'Багио': 'Baguio', 'Ранчи': 'Ranchi',
                    'Гургаон': 'Gurgaon', 'Тирупур': 'Tirupur', 'Ришикеш': 'Rishikesh', 'Читтагонг': 'Chittagong',
                    'Морадабад': 'Moradabad', 'Тэгу': 'Daegu', 'Самуи': 'Ko Samui', 'Медан': 'Medan',
                    'Триссур': 'Thrissur', 'Ко Тао': 'Ko Tao', 'Палембанг': 'Palembang', 'Хуэйчжоу': 'Huizhou',
                    'Са Па': 'Sa Pa', 'Ко Чанг': 'Ko Chang', 'Лангкави': 'Langkawi', 'Малаппурам': 'Malappuram',
                    'Наха': 'Naha', 'Денпасар': 'Denpasar', 'Гувахати': 'Guwahati', 'Джокьякарта': 'Yogyakarta',
                    'Суракарта': 'Surakarta', 'Кхулна': 'Khulna', 'Токио': 'Tokyo', 'Сринагар': 'Srinagar',
                    'Кванджу': 'Gwangju', 'Калькутта': 'Kolkata', 'Варанаси': 'Varanasi', 'Раджкот': 'Rajkot',
                    'Хуайбэй': 'Huaibei', 'Хуайань': "Huai'an", 'Хуайнань': 'Huainan', 'Тэджон': 'Daejeon',
                    'Гуйян': 'Guiyang', 'Каннур': 'Kannur', 'Коимбаторе': 'Coimbatore', 'Дунъин': 'Dongying',
                    'Ляньюньган': 'Lianyungang', 'Цзинань': 'Jinan', 'Шаньтоу': 'Shantou', 'Кута': 'Kuta',
                    'Цзямуси': 'Jiamusi', 'Дург': 'Durg', 'Лючжоу': 'Liuzhou', 'Сурат': 'Surat', 'Васай': 'Vasai',
                    'Душанбе': 'Dushanbe', 'Коллам': 'Kollam', 'Сувон': 'Suwon', 'Чунцин': 'Chongqing',
                    'Бхубанешвар': 'Bhubaneswar', 'Дунгуань': 'Dongguan', 'Цыси': 'Cixi', 'Мултан': 'Multan',
                    'Цюаньчжоу': 'Quanzhou', 'Кинмэнь': 'Kinmen', 'Чаншу': 'Changshu', 'Бишкек': 'Bishkek',
                    'Вэйфан': 'Weifang', 'Си Ань': 'Xi An', 'Барейли': 'Bareilly', 'Аньянг': 'Anyang',
                    'Асансол': 'Asansol', 'Бахавалпур': 'Bahawalpur', 'Цзилинь': 'Jilin', 'Астана': 'Astana',
                    'Цзянмэнь': 'Jiangmen', 'Гуджранвала': 'Gujranwala', 'Ханчжоу': 'Hangzhou', 'Наньчан': 'Nanchang',
                    'Удонтхани': 'Udon Thani', 'Чжаньцзян': 'Zhanjiang', 'Куньмин': 'Kunming', 'Наньнин': 'Nanning',
                    'Исламабад': 'Islamabad', 'Карачи': 'Karachi', 'Хуахин': 'Hua Hin', 'Шицзячжуан': 'Shijiazhuang',
                    'Сиалкот': 'Sialkot', 'Тайчжоу': 'Taizhou', 'Чжуншань': 'Zhongshan', 'Шанхай': 'Shanghai',
                    'Ичан': 'Yichang', 'Кветта': 'Quetta', 'Чэнду': 'Chengdu', 'Пекин': 'Beijing',
                    'Саргодха': 'Sargodha', 'Равалпинди': 'Rawalpindi', 'Пуна': 'Pune', 'Линьи': 'Linyi',
                    'Вьентьян': 'Vientiane', 'Зуньи': 'Zunyi', 'Чжэнчжоу': 'Zhengzhou', 'Таншань': 'Tangshan',
                    'Боракай': 'Boracay', 'Наньян': 'Nanyang', 'Пешавар': 'Peshawar',
                    'Бандар Сери Бегаван': 'Bandar Seri Begawan', 'Яншо': 'Yangshuo', 'Нинбо': 'Ningbo',
                    'Тайюань': 'Taiyuan', 'Синин': 'Xining', 'Чжоукоу': 'Zhoukou', 'Сянтан': 'Xiangtan',
                    'Яньтай': 'Yantai', 'Чжучжоу': 'Zhuzhou', 'Хух-Хото': 'Hohhot', 'Ланьчжоу': 'Lanzhou',
                    'Вэньлин': 'Wenling', 'Дили': 'Dili', 'Фучжоу': 'Fuzhou', 'Цзыбо': 'Zibo', 'Нашик': 'Nashik',
                    'Фейсалабад': 'Faisalabad', 'Шаосин': 'Shaoxing', 'Ханьдань': 'Handan', 'Ченнаи': 'Chennai',
                    'Лоян': 'Luoyang', 'Датун': 'Datong', 'Баодин': 'Baoding', 'Шэньчжэнь': 'Shenzhen',
                    'Куньшань': 'Kunshan', 'Тайчжун': 'Taichung', 'Индор': 'Indore', 'Уху': 'Wuhu',
                    'Сиануквиль': 'Sihanoukville', 'Нанкин': 'Nanjing', 'Дакка': 'Dhaka', 'Сендай': 'Sendai',
                    'Бхопал': 'Bhopal', 'Цицикар': 'Qiqihar', 'Харбин': 'Harbin', 'Путянь': 'Putian',
                    'Сюйчжоу': 'Xuzhou', 'Ван Вьенг': 'Vang Vieng', 'Ко Липе': 'Ko Lipe', 'Чанчунь': 'Changchun',
                    'Циньхуандао': 'Qinhuangdao', 'Ао Нанг': 'Ao Nang', 'Тан': 'Thane', 'Наньтун': 'Nantong',
                    'Тяньцзинь': 'Tianjin', 'Пхеньян': 'Pyongyang', 'Дханбад': 'Dhanbad', 'Иньчуань': 'Yinchuan',
                    'Урумчи': 'Urumqi', 'Ко Пхи-Пхи': 'Ko Phi Phi', 'Далянь': 'Dalian', 'Вонсан': 'Wonsan',
                    'Фукуока': 'Fukuoka', 'Чжучэн': 'Zhucheng', 'Чжухай': 'Zhuhai',
                    'Тируванантапурам': 'Thiruvananthapuram', 'Чжанцзякоу': 'Zhangjiakou', 'Циндао': 'Qingdao',
                    'Райпур': 'Raipur', 'Улан-Батор': 'Ulaanbaatar', 'Чифэн': 'Chifeng', 'Фушунь': 'Fushun',
                    'Шэньян': 'Shenyang', 'Ухань': 'Wuhan', 'Цзясин': 'Jiaxing', 'Окаяма': 'Okayama',
                    'Кэсон': 'Kaesong', 'Кэчхон': 'Kaechon', 'Макао': 'Macau', 'Хэфэй': 'Hefei', 'Камияма': 'Kamiyama',
                    'Гуйлинь': 'Guilin', 'Синуйцзю': 'Sinuiju', 'Китакюсю': 'Kitakyushu',
                    'Окинава Сити': 'Okinawa City', 'Баотоу': 'Baotou', 'Вэньчжоу': 'Wenzhou', 'Танчхон': 'Tanchon',
                    'Аллахабад': 'Allahabad', 'Нагоя': 'Nagoya', 'Убе': 'Ube', 'Осака': 'Osaka', 'Жуйань': "Rui'an",
                    'Сямынь': 'Xiamen', 'Пунин': 'Puning', 'Остров Цусима': 'Tsushima Island', 'Сучжоу': 'Suzhou',
                    'Нагасаки': 'Nagasaki', 'Янчжоу': 'Yangzhou', 'Чжанчжоу': 'Zhangzhou', 'Хамхунг': 'Hamhung',
                    'Кобе': 'Kobe', 'Фошань': 'Foshan', 'Чанша': 'Changsha', 'Аньшань': 'Anshan', 'Чонджин': 'Chongjin',
                    'Иу': 'Yiwu', 'Кагосима': 'Kagoshima', 'Чжанцзяган': 'Zhangjiagang', 'Киото': 'Kyoto',
                    'Саривон': 'Sariwon', 'Ашгабат': 'Ashgabat', 'Хучжоу': 'Huzhou', 'Нампо': 'Nampo',
                    'Сянъян': 'Xiangyang', 'Мале': 'Male', 'Вэйхай': 'Weihai', 'Тенчжоу': 'Tengzhou',
                    'Доробо': 'Dorobō', 'Саппоро': 'Sapporo', 'Хамамацу': 'Hamamatsu', 'Хиросима': 'Hiroshima',
                    'Иокогама': 'Yokohama', 'Наго': 'Nago', 'Уси': 'Wuxi', 'Томск': 'Tomsk',
                    'Владивосток': 'Vladivostok', 'Нейпьидо': 'Naypyidaw', 'Красноярск': 'Krasnoyarsk', 'Омск': 'Omsk',
                    'Мандалай': 'Mandalay', 'Новосибирск': 'Novosibirsk', 'Кабул': 'Kabul', 'Янгон': 'Yangon',
                    'Лиссабон': 'Lisbon', 'Гран-Канария': 'Gran Canaria', 'Тимишоара': 'Timisoara',
                    'Мадейра': 'Madeira', 'Портиман': 'Portimão', 'Фуэртевентура': 'Fuerteventura',
                    'Эрисейра': 'Ericeira', 'Порту': 'Porto', 'Белград': 'Belgrade', 'Берлин': 'Berlin',
                    'Тенерифе': 'Tenerife', 'Варшава': 'Warsaw', 'Брашов': 'Brasov', 'Тбилиси': 'Tbilisi',
                    'Варна': 'Varna', 'София': 'Sofia', 'Стамбул': 'Istanbul', 'Лондон': 'London', 'Клуж': 'Cluj',
                    'Вроцлав': 'Wrocław', 'Азорские острова': 'Azores', 'Будапешт': 'Budapest', 'Банско': 'Bansko',
                    'Майорка': 'Mallorca', 'Дрезден': 'Dresden', 'Таллинн': 'Tallinn', 'Загреб': 'Zagreb',
                    'Плоешти': 'Ploiesti', 'Пловдив': 'Plovdiv', 'Бухарест': 'Bucharest', 'Брно': 'Brno',
                    'Краков': 'Kraków', 'Анталия': 'Antalya', 'Скопье': 'Skopje', 'Познань': 'Poznan',
                    'Барселона': 'Barcelona', 'Мюнхен': 'Munich', 'Щецин': 'Szczecin', 'Задар': 'Zadar',
                    'Нови Сад': 'Novi Sad', 'Констанца': 'Constanta', 'Мостар': 'Mostar', 'Любляна': 'Ljubljana',
                    'Алания': 'Alanya', 'Афины': 'Athens', 'Гданьск': 'Gdansk', 'Брага': 'Braga',
                    'Братислава': 'Bratislava', 'Ниш': 'Nis', 'Ереван': 'Yerevan', 'Гронинген': 'Groningen',
                    'Дубровник': 'Dubrovnik', 'Амстердам': 'Amsterdam', 'Фаро': 'Faro', 'Адана': 'Adana',
                    'Авейру': 'Aveiro', 'Лейпциг': 'Leipzig', 'Лодзь': 'Lodz', 'Риека': 'Rijeka', 'Крайова': 'Craiova',
                    'Рига': 'Riga', 'Измир': 'Izmir', 'Стокгольм': 'Stockholm', 'Приштина': 'Pristina',
                    'Аликанте': 'Alicante', 'Кишинев': 'Chisinau', 'Тирана': 'Tirana', 'Копенгаген': 'Copenhagen',
                    'Бургас': 'Burgas', 'Франкфурт': 'Frankfurt', 'Коимбра': 'Coimbra', 'Сплит': 'Split',
                    'Менорка': 'Menorca', 'Валенсия': 'Valencia', 'Кошице': 'Kosice', 'Гамбург': 'Hamburg',
                    'Яссы': 'Iasi', 'Тампере': 'Tampere', 'Пафос': 'Paphos', 'Мальме': 'Malmö',
                    'Коста-да-Капарика': 'Costa da Caparica', 'Нюрнберг': 'Nuremberg', 'Ахен': 'Aachen',
                    'Люблин': 'Lublin', 'Хельсинки': 'Helsinki', 'Анкара': 'Ankara', 'Монпелье': 'Montpellier',
                    'Прага': 'Prague', 'Газиантеп': 'Gaziantep', 'Озеро Балатон': 'Lake Balaton', 'Лейден': 'Leiden',
                    'Баня-Лука': 'Banja Luka', 'Осиек': 'Osijek', 'Батуми': 'Batumi', 'Турку': 'Turku',
                    'Тарту': 'Tartu', 'Сараево': 'Sarajevo', 'Катовице': 'Katowice', 'Осло': 'Oslo',
                    'Ньюкасл-апон-Тайн': 'Newcastle Upon Tyne', 'Роттердам': 'Rotterdam', 'Гори': 'Gori',
                    'Гетеборг': 'Gothenburg', 'Штутгарт': 'Stuttgart', 'Хаген': 'Hagen', 'Лилль': 'Lille',
                    'Карлсруэ': 'Karlsruhe', 'Бат': 'Bath', 'Оулу': 'Oulu', 'Йена': 'Jena', 'Каунас': 'Kaunas',
                    'Абердин': 'Aberdeen', 'Дублин': 'Dublin', 'Подгорица': 'Podgorica', 'Грац': 'Graz',
                    'Бремен': 'Bremen', 'Инсбрук': 'Innsbruck', 'Ханья': 'Chania', 'Тулуза': 'Toulouse',
                    'Ноттингем': 'Nottingham', 'Лион': 'Lyon', 'Цюрих': 'Zurich', 'Кельн': 'Cologne', 'Баку': 'Baku',
                    'Лестер': 'Leicester', 'Вильнюс': 'Vilnius', 'Ковентри': 'Coventry', 'Вена': 'Vienna',
                    'Рейкьявик': 'Reykjavik', 'Лутон': 'Luton', 'Женева': 'Geneva', 'Ницца': 'Nice', 'Бодрум': 'Bodrum',
                    'Мадрид': 'Madrid', 'Клайпеда': 'Klaipeda', 'Нортгемптон': 'Northampton', 'Будва': 'Budva',
                    'Жешув': 'Rzeszow', 'Борнмут': 'Bournemouth', 'Конья': 'Konya', 'Ювяскюля': 'Jyvaskyla',
                    'Венеция': 'Venice', 'Портсмут': 'Portsmouth', 'Глазго': 'Glasgow', 'Никосия': 'Nicosia',
                    'Гейдельберг': 'Heidelberg', 'Патры': 'Patras', 'Эспоо': 'Espoo', 'Палермо': 'Palermo',
                    'Лимассол': 'Limassol', 'Шумперк': 'Šumperk', 'Бристоль': 'Bristol', 'Ренн': 'Rennes',
                    'Дортмунд': 'Dortmund', 'Билефельд': 'Bielefeld', 'Цавтат': 'Cavtat', 'Ла-Корунья': 'A Coruna',
                    'Париж': 'Paris', 'Гаага': 'The Hague', 'Неймеген': 'Nijmegen', 'Салоники': 'Thessaloniki',
                    'Лидс': 'Leeds', 'Утрехт': 'Utrecht', 'Гент': 'Ghent', 'Озеро Комо': 'Lake Como',
                    'Брюссель': 'Brussels', 'Памплона': 'Pamplona', 'Ливерпуль': 'Liverpool', 'Бреда': 'Breda',
                    'Малага': 'Malaga', 'Хаддерсфилд': 'Huddersfield', 'Севилья': 'Seville', 'Нант': 'Nantes',
                    'Оксфорд': 'Oxford', 'Котор': 'Kotor', 'Корк': 'Cork', 'Орхус': 'Aarhus', 'Хоф': 'Hof',
                    'Саутгемптон': 'Southampton', 'Ганновер': 'Hannover', 'Берн': 'Bern', 'Голуэй': 'Galway',
                    'Рим': 'Rome', 'Гранада': 'Granada', 'Кассель': 'Kassel', 'Марбелья': 'Marbella',
                    'Гренобль': 'Grenoble', 'Хвар': 'Hvar', 'Эйндховен': 'Eindhoven', 'Страсбург': 'Strasbourg',
                    'Хавеа': 'Javea', 'Флоренция': 'Florence', 'Кардифф': 'Cardiff', 'Ольборг': 'Aalborg',
                    'Халл': 'Hull', 'Йорк': 'York', 'Кембридж': 'Cambridge', 'Зволле': 'Zwolle', 'Антверпен': 'Antwerp',
                    'Бар': 'Bar', 'Норвич': 'Norwich', 'Схевенинген': 'Scheveningen', 'Милан': 'Milan',
                    'Эрланген': 'Erlangen', 'Тилбург': 'Tilburg', 'Марсель': 'Marseille', 'Родос': 'Rhodes',
                    'Левен': 'Leuven', 'Зандворт': 'Zandvoort', 'Шеффилд': 'Sheffield', 'Компорта': 'Comporta',
                    'Падуя': 'Padova', 'Монако': 'Monaco', 'Челтнем': 'Cheltenham', 'Девентер': 'Deventer',
                    'Тронхейм': 'Trondheim', 'Арнем': 'Arnhem', 'Шрусбери': 'Shrewsbury', 'Ларнака': 'Larnaca',
                    'Леуварден': 'Leeuwarden', 'Лелистад': 'Lelystad', 'Лансароте': 'Lanzarote', 'Берген': 'Bergen',
                    'Харлем': 'Haarlem', 'Тромсе': 'Tromso', 'Тексель': 'Texel', 'Неаполь': 'Naples',
                    'Бордо': 'Bordeaux', 'Триест': 'Trieste', 'Канны': 'Cannes', 'Брюгге': 'Bruges', 'Мамайя': 'Mamaia',
                    'Лугано': 'Lugano', 'Пиза': 'Pisa', 'Гибралтар': 'Gibraltar', 'Шамони': 'Chamonix',
                    'Сан-Себастьян': 'San Sebastian', 'Слима': 'Sliema', 'Базель': 'Basel',
                    'Андорра-ла-Велья': 'Andorra la Vella', 'Алмере': 'Almere', 'Дармштадт': 'Darmstadt',
                    'Сент-Хелиер': 'Saint Helier', 'Анси': 'Annecy', 'Люксембург': 'Luxembourg', 'Ибица': 'Ibiza',
                    'Болонья': 'Bologna', 'Тренто': 'Trento', 'Лозанна': 'Lausanne', 'Бурса': 'Bursa',
                    'Зальцбург': 'Salzburg', 'Арендал': 'Arendal', 'Биарриц': 'Biarritz', 'Модена': 'Modena',
                    'Дюссельдорф': 'Dusseldorf', 'Генуя': 'Genoa', 'Олесунн': 'Alesund', 'Ретимно': 'Rethymno',
                    'Торсхавн': 'Torshavn', 'Брайтон': 'Brighton', 'Интерлакен': 'Interlaken', 'Рованиеми': 'Rovaniemi',
                    'Дижон': 'Dijon', 'Санторини': 'Santorini', 'Миконос': 'Mykonos', 'Трир': 'Trier',
                    'Св. Галлен': 'St. Gallen', 'Кальяри': 'Cagliari', 'Авеллино': 'Avellino', 'Тревизо': 'Treviso',
                    'Тарифа': 'Tarifa', 'Феррара': 'Ferrara', 'Римини': 'Rimini', 'Верона': 'Verona',
                    'Бильбао': 'Bilbao', 'Руан': 'Rouen', 'Лукка': 'Lucca', 'Белфаст': 'Belfast', 'Амальфи': 'Amalfi',
                    'Авиньон': 'Avignon', 'Бари': 'Bari', 'Монца': 'Monza', 'Ватикан': 'Vatican City', 'Турин': 'Turin',
                    'Сиена': 'Siena', 'Аяччо': 'Ajaccio', 'Эксетер': 'Exeter', 'Обнинск': 'Obninsk',
                    'Новочеркасск': 'Novocherkassk', 'Ивано-Франковск': 'Ivano-Frankivsk', 'Сочи': 'Sochi',
                    'Калининград': 'Kaliningrad', 'Ульяновск': 'Ulyanovsk', 'Ижевск': 'Izhevsk',
                    'Кривой Рог': 'Krivoy-Rog', 'Львов': 'Lviv', 'Краснодар': 'Krasnodar', 'Саратов': 'Saratov',
                    'Днепр': 'Dnipro', 'Волгоград': 'Volgograd', 'Уфа': 'Ufa', 'Ростов-на-Дону': 'Rostov-on-Don',
                    'Челябинск': 'Chelyabinsk', 'Казань': 'Kazan', 'Самара': 'Samara', 'Нижний': 'Nizhny',
                    'Харьков': 'Kharkiv', 'Екатеринбург': 'Yekaterinburg', 'Минск': 'Minsk', 'Киев': 'Kyiv',
                    'Санкт-Петербург': 'Saint Petersburg', 'Москва': 'Moscow', 'Иннополис': 'Innopolis'}

for i in range(len(cities_eng)):
    cities_ru_to_eng[cities_ru[i]] = cities_eng[i]
